"""
THEeye - Data Analysis Module
Generates R and Stata 18 code for statistical analysis based on
extracted research data and user-specified methods.

Supported analyses:
  - Descriptive statistics
  - Correlation analysis
  - OLS regression
  - Panel data (fixed/random effects)
  - Logistic regression
  - Instrumental variables (2SLS)
  - Time series (ARIMA, VAR)
  - Difference-in-Differences
  - Robustness checks
"""


# ---------------------------------------------------------------------------
# R Code Generation
# ---------------------------------------------------------------------------

def generate_r_code(method: str, variables: dict, options: dict = None) -> str:
    """
    Generate R code for the specified statistical method.

    Args:
        method: One of the supported analysis types
        variables: Dict with variable names (dependent, independent, control, etc.)
        options: Additional options (robust_se, cluster, etc.)
    """
    options = options or {}
    dep = variables.get("dependent", "y")
    indep = variables.get("independent", [])
    controls = variables.get("controls", [])
    data_file = variables.get("data_file", "data.csv")
    cluster_var = options.get("cluster_var", "")

    all_indep = indep + controls
    indep_str = " + ".join(all_indep) if all_indep else "x"

    header = f"""# ============================================================
# THEeye - Generated R Code
# Analysis: {method}
# Generated: Auto-generated by THEeye Research Platform
# ============================================================

# Load required libraries
library(tidyverse)
library(sandwich)
library(lmtest)
library(stargazer)
"""

    if method == "descriptive":
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Descriptive Statistics
summary(data)

# Correlation matrix
cor_matrix <- cor(data[, c("{dep}", "{'", "'.join(all_indep)}")], use = "complete.obs")
print(cor_matrix)

# Visualize distributions
data %>%
  select({dep}, {', '.join(all_indep[:5])}) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  ggplot(aes(x = value)) +
  geom_histogram(bins = 30, fill = "steelblue", color = "white") +
  facet_wrap(~ variable, scales = "free") +
  theme_minimal() +
  labs(title = "Variable Distributions")
"""

    elif method == "correlation":
        vars_str = '", "'.join(all_indep)
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Correlation Analysis
vars <- c("{dep}", "{vars_str}")
cor_data <- data[, vars]

# Pearson correlation
cor_pearson <- cor(cor_data, use = "complete.obs", method = "pearson")
print("Pearson Correlation:")
print(cor_pearson)

# Spearman correlation
cor_spearman <- cor(cor_data, use = "complete.obs", method = "spearman")
print("Spearman Correlation:")
print(cor_spearman)

# Correlation plot
library(corrplot)
corrplot(cor_pearson, method = "color", type = "upper",
         addCoef.col = "black", tl.col = "black", tl.srt = 45,
         title = "Correlation Matrix", mar = c(0, 0, 2, 0))

# Significance test
library(Hmisc)
rcorr_result <- rcorr(as.matrix(cor_data))
print(rcorr_result)
"""

    elif method == "ols":
        robust = options.get("robust_se", True)
        code = header + f"""
# Load data
data <- read.csv("{data_file}")

# OLS Regression
model <- lm({dep} ~ {indep_str}, data = data)

# Summary
summary(model)

# Robust standard errors
"""
        if robust:
            code += f"""
# Heteroskedasticity-robust standard errors
robust_se <- vcovHC(model, type = "HC1")
robust_model <- coeftest(model, vcov = robust_se)
print("Robust Standard Errors:")
print(robust_model)
"""
        if cluster_var:
            code += f"""
# Clustered standard errors
cluster_se <- vcovCL(model, cluster = ~{cluster_var}, type = "HC1")
cluster_model <- coeftest(model, vcov = cluster_se)
print("Clustered Standard Errors:")
print(cluster_model)
"""
        code += f"""
# Publication-ready table
stargazer(model, type = "text", title = "OLS Regression Results",
          dep.var.labels = "{dep}",
          covariate.labels = c("{'", "'.join(all_indep)}"),
          star.cutoffs = c(0.1, 0.05, 0.01))

# Diagnostic plots
par(mfrow = c(2, 2))
plot(model)
"""
        return code

    elif method == "panel_fixed":
        entity_var = variables.get("entity", "country")
        time_var = variables.get("time", "year")
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Install and load plm if needed
# install.packages("plm")
library(plm)

# Convert to panel data
pdata <- pdata.frame(data, index = c("{entity_var}", "{time_var}"))

# Fixed Effects Model
fe_model <- plm({dep} ~ {indep_str}, data = pdata, model = "within")
summary(fe_model)

# Random Effects Model
re_model <- plm({dep} ~ {indep_str}, data = pdata, model = "random")
summary(re_model)

# Hausman Test (FE vs RE)
hausman_test <- phtest(fe_model, re_model)
print("Hausman Test (H0: Random Effects preferred):")
print(hausman_test)

# Clustered standard errors for FE
cluster_se <- vcovHC(fe_model, cluster = "group", type = "HC1")
fe_robust <- coeftest(fe_model, vcov = cluster_se)
print("Fixed Effects with Clustered SE:")
print(fe_robust)

# Publication table
stargazer(fe_model, re_model, type = "text",
          title = "Panel Data Regression Results",
          dep.var.labels = "{dep}",
          column.labels = c("Fixed Effects", "Random Effects"),
          star.cutoffs = c(0.1, 0.05, 0.01))
"""

    elif method == "logistic":
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Logistic Regression
logit_model <- glm({dep} ~ {indep_str}, data = data, family = binomial(link = "logit"))
summary(logit_model)

# Probit Regression (alternative)
probit_model <- glm({dep} ~ {indep_str}, data = data, family = binomial(link = "probit"))
summary(probit_model)

# Marginal effects
# install.packages("margins")
library(margins)
logit_margins <- margins(logit_model)
print("Marginal Effects (Logit):")
summary(logit_margins)

# Odds ratios
odds_ratios <- exp(coef(logit_model))
print("Odds Ratios:")
print(odds_ratios)

# Confusion matrix and accuracy
predicted <- ifelse(fitted(logit_model) > 0.5, 1, 0)
confusion_matrix <- table(Actual = data${dep}, Predicted = predicted)
print("Confusion Matrix:")
print(confusion_matrix)
accuracy <- sum(diag(confusion_matrix)) / sum(confusion_matrix)
print(paste("Accuracy:", round(accuracy * 100, 2), "%"))

# ROC curve
# install.packages("pROC")
library(pROC)
roc_curve <- roc(data${dep}, fitted(logit_model))
plot(roc_curve, main = "ROC Curve")
print(paste("AUC:", auc(roc_curve)))

# Publication table
stargazer(logit_model, probit_model, type = "text",
          title = "Binary Choice Models",
          dep.var.labels = "{dep}",
          star.cutoffs = c(0.1, 0.05, 0.01))
"""

    elif method == "iv_2sls":
        instruments = variables.get("instruments", ["z1"])
        instr_str = " + ".join(instruments)
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Install and load AER if needed
# install.packages("AER")
library(AER)

# First Stage Regression
first_stage <- lm({indep[0] if indep else 'x'} ~ {instr_str} + {' + '.join(controls)}, data = data)
summary(first_stage)

# F-test for instrument strength
first_stage_f <- linearHypothesis(first_stage, c("{'= "'.join(instruments)}=0"))
print("First Stage F-statistic:")
print(first_stage_f)

# 2SLS / IV Regression
iv_model <- ivreg({dep} ~ {indep_str} | {instr_str} + {' + '.join(controls)}, data = data)
summary(iv_model, diagnostics = TRUE)

# Robust standard errors
iv_robust_se <- vcovHC(iv_model, type = "HC1")
iv_robust <- coeftest(iv_model, vcov = iv_robust_se)
print("IV Regression with Robust SE:")
print(iv_robust)

# Compare OLS and IV
ols_model <- lm({dep} ~ {indep_str}, data = data)
stargazer(ols_model, iv_model, type = "text",
          title = "OLS vs IV Regression",
          column.labels = c("OLS", "2SLS"),
          dep.var.labels = "{dep}",
          star.cutoffs = c(0.1, 0.05, 0.01))
"""

    elif method == "did":
        treatment = variables.get("treatment", "treated")
        post = variables.get("post", "post")
        interaction = f"{treatment}:{post}"
        did_indep = f"{treatment} + {post} + {interaction}"
        if controls:
            did_indep += " + " + " + ".join(controls)
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Difference-in-Differences
did_model <- lm({dep} ~ {did_indep}, data = data)
summary(did_model)

# Robust standard errors
did_robust_se <- vcovHC(did_model, type = "HC1")
did_robust <- coeftest(did_model, vcov = did_robust_se)
print("DiD with Robust SE:")
print(did_robust)

# Parallel trends visualization
library(ggplot2)
data %>%
  group_by({post}, {treatment}) %>%
  summarise(mean_outcome = mean({dep}, na.rm = TRUE), .groups = "drop") %>%
  ggplot(aes(x = {post}, y = mean_outcome, color = as.factor({treatment}))) +
  geom_line(size = 1) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "Parallel Trends Assumption Check",
       x = "Period", y = "Mean Outcome",
       color = "Treatment Group")

# With entity and time fixed effects (Two-way FE DiD)
# install.packages("fixest")
library(fixest)
twoway_did <- feols({dep} ~ {interaction} | {' + '.join(variables.get('entity', ['country']))} + {variables.get('time', 'year')}, data = data)
summary(twoway_did)
"""

    elif method == "time_series":
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Install packages if needed
# install.packages(c("tseries", "forecast", "vars"))
library(tseries)
library(forecast)
library(vars)

# Convert to time series
ts_data <- ts(data${dep}, frequency = 12)  # Adjust frequency as needed

# Stationarity test (ADF)
adf_test <- adf.test(ts_data)
print("Augmented Dickey-Fuller Test:")
print(adf_test)

# If non-stationary, difference
if (adf_test$p.value > 0.05) {{
    ts_data_diff <- diff(ts_data)
    adf_test_diff <- adf.test(ts_data_diff)
    print("ADF Test on Differenced Series:")
    print(adf_test_diff)
}} else {{
    ts_data_diff <- ts_data
}}

# ARIMA model selection
auto_arima <- auto.arima(ts_data)
print("Auto ARIMA:")
print(summary(auto_arima))

# Forecast
forecast_result <- forecast(auto_arima, h = 12)
plot(forecast_result, main = "ARIMA Forecast")

# VAR model (if multiple variables)
var_data <- data[, c("{dep}", "{'", "'.join(all_indep[:3])}")]
var_model <- VAR(var_data, p = 2, type = "const")
summary(var_model)

# Granger causality test
for (v in c("{'", "'.join(all_indep[:3])}")) {{
    granger_test <- grangertest({dep} ~ v, data = var_data)
    print(paste("Granger Causality:", {dep}, "->", v))
    print(granger_test)
}}
"""

    elif method == "robustness":
        return header + f"""
# Load data
data <- read.csv("{data_file}")

# Main model
main_model <- lm({dep} ~ {indep_str}, data = data)

# Robustness Checks

# 1. Alternative sample (remove outliers)
data_trimmed <- data[data${dep} > quantile(data${dep}, 0.05) &
                     data${dep} < quantile(data${dep}, 0.95), ]
model_trimmed <- lm({dep} ~ {indep_str}, data = data_trimmed)

# 2. Alternative specification (add quadratic terms)
indep_quad <- paste0("I(", c("{'", "'.join(all_indep)}"), "^2)")
model_quad <- lm({dep} ~ {indep_str} + {' + '.join(indep_quad)}, data = data)

# 3. Alternative standard errors (clustered)
{'cluster_se <- vcovCL(main_model, cluster = ~' + cluster_var + ', type = "HC1")' if cluster_var else 'cluster_se <- vcovHC(main_model, type = "HC1")'}
model_clustered <- coeftest(main_model, vcov = cluster_se)

# 4. Bootstrap standard errors
library(boot)
boot_fn <- function(data, indices) {{
    coef(lm({dep} ~ {indep_str}, data = data[indices, ]))
}}
boot_results <- boot(data, boot_fn, R = 1000)
print("Bootstrap Results:")
print(boot_results)

# Compare all specifications
stargazer(main_model, model_trimmed, model_quad, type = "text",
          title = "Robustness Checks",
          column.labels = c("Baseline", "Trimmed", "Quadratic"),
          dep.var.labels = "{dep}",
          star.cutoffs = c(0.1, 0.05, 0.01))

# Oster (2019) bounds for omitted variable bias
# install.packages("robomit")
library(robomit)
oster_bounds <- oster(dv = "{dep}", cont = c("{'", "'.join(all_indep)}"),
                      uncont = c("{'", "'.join(indep[:1])}"), data = data)
print("Oster Bounds:")
print(oster_bounds)
"""

    return header + f"\n# Method '{method}' not recognized. Please choose from: ols, panel_fixed, logistic, iv_2sls, did, time_series, robustness, descriptive, correlation\n"


# ---------------------------------------------------------------------------
# Stata 18 Code Generation
# ---------------------------------------------------------------------------

def generate_stata_code(method: str, variables: dict, options: dict = None) -> str:
    """
    Generate Stata 18 do-file code for the specified statistical method.
    """
    options = options or {}
    dep = variables.get("dependent", "y")
    indep = variables.get("independent", [])
    controls = variables.get("controls", [])
    data_file = variables.get("data_file", "data.dta")
    cluster_var = options.get("cluster_var", "")

    all_indep = indep + controls
    indep_str = " ".join(all_indep) if all_indep else "x"

    header = f"""* ============================================================
* THEeye - Generated Stata 18 Code
* Analysis: {method}
* Generated: Auto-generated by THEeye Research Platform
* ============================================================

clear all
set more off
set mem 100m

* Load data
use "{data_file}", clear

* Set up log
log using "theeye_{method}.log", replace text

"""

    if method == "descriptive":
        return header + f"""
* Descriptive Statistics
summarize {dep} {indep_str}

* Detailed statistics
tabstat {dep} {indep_str}, stat(mean sd min p25 p50 p75 max n)

* Correlation matrix
pwcorr {dep} {indep_str}, sig star(0.05)

* Visualize distributions
histogram {dep}, frequency title("Distribution of {dep}")
graph export "hist_{dep}.png", replace

log close
"""

    elif method == "correlation":
        vars_str = " ".join([dep] + all_indep)
        return header + f"""
* Correlation Analysis
pwcorr {vars_str}, sig star(0.05)

* Spearman rank correlation
spearman {vars_str}, star(0.05)

* Pairwise scatter plots
graph matrix {vars_str}, half

* Export correlation matrix
estpost summarize {vars_str}
esttab using "correlation_matrix.csv", csv replace

log close
"""

    elif method == "ols":
        robust = options.get("robust_se", True)
        code = header + f"""
* OLS Regression
regress {dep} {indep_str}
estimates store ols_basic

"""
        if robust:
            code += """
* Heteroskedasticity-robust standard errors
regress DEP INDEP, robust
estimates store ols_robust

""".replace("DEP", dep).replace("INDEP", indep_str)

        if cluster_var:
            code += f"""
* Clustered standard errors
regress {dep} {indep_str}, vce(cluster {cluster_var})
estimates store ols_clustered

"""
        code += f"""
* Export results
esttab ols_basic ols_robust using "ols_results.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("OLS Regression Results") ///
    label varlabels({dep} "{dep}")

* Diagnostic tests
* Heteroskedasticity test
estat hettest

* Multicollinearity (VIF)
vif

* Normality of residuals
predict residuals, residuals
histogram residuals, normal
swilk residuals

log close
"""
        return code

    elif method == "panel_fixed":
        entity_var = variables.get("entity", "country")
        time_var = variables.get("time", "year")
        return header + f"""
* Set panel data structure
xtset {entity_var} {time_var}

* Fixed Effects Model
xtreg {dep} {indep_str}, fe
estimates store fe_model

* Random Effects Model
xtreg {dep} {indep_str}, re
estimates store re_model

* Hausman Test
hausman fe_model re_model

* Fixed Effects with cluster-robust SE
xtreg {dep} {indep_str}, fe vce(cluster {entity_var})
estimates store fe_robust

* Export results
esttab fe_model re_model fe_robust using "panel_results.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("Panel Data Regression Results") ///
    mtitles("Fixed Effects" "Random Effects" "FE Clustered")

* Between estimator
xtreg {dep} {indep_str}, be
estimates store be_model

* F-test for entity fixed effects
xttest0

log close
"""

    elif method == "logistic":
        return header + f"""
* Logistic Regression
logit {dep} {indep_str}
estimates store logit_model

* Probit Regression (alternative)
probit {dep} {indep_str}
estimates store probit_model

* Marginal effects (at means)
margins, dydx(*) atmeans

* Average marginal effects
margins, dydx(*)

* Odds ratios
logit {dep} {indep_str}, or
estimates store odds_ratios

* Predicted probabilities
predict y_hat, pr

* Classification table
estat classification

* ROC curve
lsens, graphplot

* Export results
esttab logit_model probit_model using "logit_results.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("Binary Choice Models") ///
    mtitles("Logit" "Probit")

log close
"""

    elif method == "iv_2sls":
        instruments = variables.get("instruments", ["z1"])
        instr_str = " ".join(instruments)
        exog_str = " ".join(controls) if controls else ""
        return header + f"""
* First Stage Regression
regress {indep[0] if indep else 'x'} {instr_str} {exog_str}
estimates store first_stage

* F-test for weak instruments
test {instr_str}

* 2SLS / IV Regression
ivregress 2sls {dep} {exog_str} ({indep[0] if indep else 'x'} = {instr_str})
estimates store iv_model

* Robust standard errors
ivregress 2sls {dep} {exog_str} ({indep[0] if indep else 'x'} = {instr_str}), robust
estimates store iv_robust

* First-stage diagnostics
estat firststage

* Overidentification test (if multiple instruments)
estat overid

* Compare OLS and IV
regress {dep} {indep_str}
estimates store ols_model

esttab ols_model iv_model iv_robust using "iv_results.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("OLS vs IV Regression") ///
    mtitles("OLS" "2SLS" "2SLS Robust")

log close
"""

    elif method == "did":
        treatment = variables.get("treatment", "treated")
        post = variables.get("post", "post")
        return header + f"""
* Difference-in-Differences

* Basic DiD
regress {dep} c.{treatment}##c.{post} { ' '.join(controls) if controls else ''}
estimates store did_basic

* With robust SE
regress {dep} c.{treatment}##c.{post} { ' '.join(controls) if controls else ''}, robust
estimates store did_robust

* With entity and time fixed effects
reghdfe {dep} c.{treatment}#c.{post} { ' '.join(controls) if controls else ''}, ///
    absorb({variables.get('entity', 'country')} {variables.get('time', 'year')}) ///
    vce(cluster {variables.get('entity', 'country')})
estimates store did_twfe

* Parallel trends test
* Generate event-study coefficients
forvalues t = -5/5 {{
    gen T`t' = 0
    replace T`t' = 1 if ({post} + `t' == {variables.get('time', 'year')}) & {treatment} == 1
}}
drop T0  // Omit reference period
reghdfe {dep} T* { ' '.join(controls) if controls else ''}, ///
    absorb({variables.get('entity', 'country')} {variables.get('time', 'year')})
coefplot, vertical yline(0) xline(5.5) ///
    title("Event Study: Parallel Trends Test")

* Export results
esttab did_basic did_robust did_twfe using "did_results.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("Difference-in-Differences Results") ///
    mtitles("Basic DiD" "Robust DiD" "Two-way FE")

log close
"""

    elif method == "time_series":
        return header + f"""
* Set time series structure
tsset {variables.get('time', 'year')}

* Unit root test (ADF)
dfuller {dep}
dfuller {dep}, trend
dfuller D.{dep}

* If non-stationary, difference
gen {dep}_diff = D.{dep}

* ARIMA model selection
varsoc {dep}
arima {dep}, arima(1,0,1)
estimates store arima_101

arima {dep}, arima(2,0,1)
estimates store arima_201

* Information criteria comparison
esttab arima_101 arima_201 using "arima_results.rtf", replace ///
    scalars("aic AIC" "bic BIC") ///
    title("ARIMA Model Comparison")

* Forecast
arima {dep}, arima(1,0,1)
predict {dep}_forecast, y
tsappend, add(12)
predict {dep}_future, y
list {variables.get('time', 'year')} {dep}_future in -12/L

* Granger causality
varsoc {dep} { ' '.join(all_indep[:3])}
var {dep} { ' '.join(all_indep[:3])}, lags(1/2)
vargranger

* Export forecast graph
tsline {dep} {dep}_future, title("Time Series Forecast")

log close
"""

    elif method == "robustness":
        return header + f"""
* Main model
regress {dep} {indep_str}
estimates store main_model

* 1. Trimmed sample (remove outliers 5th-95th percentile)
centile {dep}, centile(5 95)
drop if {dep} < r(r1) | {dep} > r(r2)
regress {dep} {indep_str}
estimates store trimmed_model

* 2. Alternative specification (log transformation)
gen ln_{dep} = ln({dep}) if {dep} > 0
regress ln_{dep} {indep_str}
estimates store log_model

* 3. With additional controls
* regress {dep} {indep_str} additional_var1 additional_var2
* estimates store extended_model

* 4. Bootstrap standard errors
bootstrap, reps(1000): regress {dep} {indep_str}
estimates store boot_model

* 5. Quantile regression
sqreg {dep} {indep_str}, quantiles(0.25 0.50 0.75)
estimates store qr_model

* Export all specifications
esttab main_model trimmed_model log_model boot_model using "robustness.rtf", replace ///
    b(3) se(3) star(* 0.10 ** 0.05 *** 0.01) ///
    title("Robustness Checks") ///
    mtitles("Baseline" "Trimmed" "Log Transform" "Bootstrap")

log close
"""

    return header + f"\n* Method '{method}' not recognized. Please choose from: ols, panel_fixed, logistic, iv_2sls, did, time_series, robustness, descriptive, correlation\n"


# ---------------------------------------------------------------------------
# Analysis Recommendations
# ---------------------------------------------------------------------------

def recommend_analysis(research_topic: str, variables: list[str], data_type: str = "cross_section") -> list[dict]:
    """
    Recommend appropriate statistical methods based on the research context.
    """
    recommendations = []

    if data_type == "panel":
        recommendations.append({
            "method": "panel_fixed",
            "name": "Panel Data (Fixed/Random Effects)",
            "rationale": "Panel data allows controlling for unobserved heterogeneity across entities",
            "priority": "high",
        })
        recommendations.append({
            "method": "did",
            "name": "Difference-in-Differences",
            "rationale": "If studying a policy change or treatment effect over time",
            "priority": "medium",
        })
    elif data_type == "time_series":
        recommendations.append({
            "method": "time_series",
            "name": "Time Series Analysis (ARIMA/VAR)",
            "rationale": "For modeling temporal dynamics and forecasting",
            "priority": "high",
        })
    else:
        recommendations.append({
            "method": "ols",
            "name": "OLS Regression",
            "rationale": "Standard starting point for cross-sectional analysis",
            "priority": "high",
        })
        recommendations.append({
            "method": "logistic",
            "name": "Logistic Regression",
            "rationale": "If the dependent variable is binary (0/1)",
            "priority": "medium",
        })
        recommendations.append({
            "method": "iv_2sls",
            "name": "Instrumental Variables (2SLS)",
            "rationale": "If endogeneity is a concern, use valid instruments",
            "priority": "medium",
        })

    recommendations.append({
        "method": "descriptive",
        "name": "Descriptive Statistics",
        "rationale": "Always start with summary statistics to understand your data",
        "priority": "essential",
    })
    recommendations.append({
        "method": "correlation",
        "name": "Correlation Analysis",
        "rationale": "Check pairwise relationships before multivariate analysis",
        "priority": "essential",
    })
    recommendations.append({
        "method": "robustness",
        "name": "Robustness Checks",
        "rationale": "Verify that results are not sensitive to specification choices",
        "priority": "high",
    })

    return recommendations


# ---------------------------------------------------------------------------
# Available Methods Registry
# ---------------------------------------------------------------------------

ANALYSIS_METHODS = {
    "descriptive": {
        "name": "Descriptive Statistics",
        "description": "Summary statistics, distributions, and visualizations",
        "category": "exploratory",
    },
    "correlation": {
        "name": "Correlation Analysis",
        "description": "Pearson and Spearman correlation matrices with significance tests",
        "category": "exploratory",
    },
    "ols": {
        "name": "OLS Regression",
        "description": "Ordinary Least Squares with robust/clustered standard errors",
        "category": "regression",
    },
    "panel_fixed": {
        "name": "Panel Data (Fixed/Random Effects)",
        "description": "Entity and time fixed effects with Hausman test",
        "category": "panel",
    },
    "logistic": {
        "name": "Logistic Regression",
        "description": "Binary choice models with marginal effects and ROC curves",
        "category": "regression",
    },
    "iv_2sls": {
        "name": "Instrumental Variables (2SLS)",
        "description": "Two-stage least squares with weak instrument diagnostics",
        "category": "regression",
    },
    "did": {
        "name": "Difference-in-Differences",
        "description": "Policy evaluation with parallel trends testing",
        "category": "causal",
    },
    "time_series": {
        "name": "Time Series (ARIMA/VAR)",
        "description": "ARIMA modeling, forecasting, and Granger causality",
        "category": "time_series",
    },
    "robustness": {
        "name": "Robustness Checks",
        "description": "Alternative specifications, bootstrap, quantile regression",
        "category": "validation",
    },
}


def get_available_methods() -> dict:
    """Get all available analysis methods."""
    return ANALYSIS_METHODS
