"""
THEeye - Document Drafting & Roadmap Engine
Generates full research document roadmaps, suggests novel research topics,
and finds open-access articles for any research field.

Supports:
  - Research Articles (Q1-Q4 journal formats)
  - Theses (Undergraduate, Graduate/Master's, PhD) in Chinese, USA, European, African, UK formats
  - Literature Reviews
  - Book Reports
  - Review Papers
  - Conference Papers
  - Research Proposals
"""

import httpx
import asyncio
import re
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import quote_plus, urlparse


# Use a proper email for OpenAlex/Crossref polite pools (faster rate limits)
CONTACT_EMAIL = "theeye.research@gmail.com"
BROWSER_UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
PLATFORM_UA = "THEeye/2.0 (AI-Assisted Research Platform; mailto:" + CONTACT_EMAIL + ")"


DISCLAIMER = (
    "ROADMAP GENERATED BY THEeye — AI-ASSISTED RESEARCH PLATFORM. "
    "This document roadmap was generated to guide your writing process. "
    "All content must be reviewed, verified, and revised by the human author(s) "
    "before any submission. AI assistance must be disclosed per journal/institution policy."
)


# ---------------------------------------------------------------------------
# Document Type Definitions
# ---------------------------------------------------------------------------

DOCUMENT_TYPES = {
    "research_article": {
        "label": "Research Article",
        "description": "Full empirical research paper for journal submission",
        "formats": {
            "Q1": "Top-tier journal (e.g., Nature, Science, top field journals). Strict structure, high novelty requirement, comprehensive methodology.",
            "Q2": "High-quality journal. Standard IMRaD structure, solid contribution, robust methodology.",
            "Q3": "Established journal. Standard structure, adequate contribution, acceptable methodology.",
            "Q4": "Emerging/regional journal. Standard structure, contextual contribution.",
            "general": "General research article format suitable for most journals.",
        },
    },
    "thesis": {
        "label": "Thesis / Dissertation",
        "description": "Academic thesis for degree completion",
        "formats": {
            "undergraduate_usa": "Undergraduate Thesis (USA Format): Introduction, Literature Review, Methodology, Results, Discussion, Conclusion, References. Typically 40-60 pages.",
            "undergraduate_uk": "Undergraduate Dissertation (UK Format): Introduction, Literature Review, Methodology, Findings, Discussion, Conclusion, Bibliography. Typically 10,000-15,000 words.",
            "undergraduate_european": "Undergraduate Thesis (European Format): Introduction, Theoretical Framework, Methodology, Empirical Analysis, Discussion, Conclusion, References. Typically 30-50 pages.",
            "undergraduate_chinese": "Undergraduate Thesis (Chinese Format): 摘要 (Abstract), 关键词 (Keywords), 引言 (Introduction), 文献综述 (Literature Review), 研究方法 (Methodology), 研究结果 (Results), 讨论 (Discussion), 结论 (Conclusion), 参考文献 (References), 致谢 (Acknowledgments). Typically 8,000-15,000 Chinese characters.",
            "undergraduate_african": "Undergraduate Project Report (African Format): Title Page, Declaration, Dedication, Acknowledgments, Abstract, Table of Contents, List of Figures/Tables, Chapter 1-5, References, Appendices. Typically 40-60 pages.",
            "graduate_usa": "Master's Thesis (USA Format): Introduction, Literature Review, Methodology, Results, Discussion, Conclusion, References, Appendices. Typically 60-100 pages.",
            "graduate_uk": "Master's Dissertation (UK Format): Introduction, Literature Review, Methodology, Results, Discussion, Conclusion, Bibliography, Appendices. Typically 15,000-20,000 words.",
            "graduate_european": "Master's Thesis (European Format): Introduction, Theoretical Framework, Literature Review, Methodology, Empirical Analysis, Discussion, Policy Implications, Conclusion, References. Typically 60-80 pages.",
            "graduate_chinese": "Master's Thesis (Chinese Format): 摘要, 关键词, 第一章 绪论, 第二章 文献综述, 第三章 理论框架, 第四章 研究方法, 第五章 实证分析, 第六章 讨论, 第七章 结论与展望, 参考文献, 致谢, 附录. Typically 30,000-50,000 Chinese characters.",
            "graduate_african": "Master's Dissertation (African Format): Title Page, Declaration, Certification, Dedication, Acknowledgments, Abstract, Table of Contents, Chapters 1-6, References, Appendices. Typically 80-120 pages.",
            "phd_usa": "PhD Dissertation (USA Format): Introduction, Literature Review (comprehensive), Theoretical Framework, Methodology, Results (multiple chapters), Discussion, Conclusion, References, Appendices. Typically 150-300 pages.",
            "phd_uk": "PhD Thesis (UK Format): Introduction, Literature Review, Methodology, Results Chapters, Discussion, Conclusion, Bibliography, Appendices. Typically 80,000-100,000 words.",
            "phd_european": "PhD Thesis (European Format): Introduction, Theoretical Framework, Literature Review, Methodology, Empirical Analysis (multiple chapters), Discussion, Policy Implications, Conclusion, References. Cumulative thesis option with published papers. Typically 150-250 pages.",
            "phd_chinese": "PhD Dissertation (Chinese Format): 摘要, 关键词, 第一章 绪论, 第二章 文献综述, 第三章 理论框架与研究假设, 第四章 研究设计与方法, 第五章 实证分析, 第六章 进一步分析, 第七章 结论与政策建议, 参考文献, 致谢, 攻读博士学位期间研究成果, 附录. Typically 80,000-150,000 Chinese characters.",
            "phd_african": "PhD Thesis (African Format): Title Page, Declaration, Certification, Dedication, Acknowledgments, Abstract, Table of Contents, List of Figures/Tables/Abbreviations, Chapters 1-7, References, Appendices. Typically 200-350 pages.",
        },
    },
    "literature_review": {
        "label": "Literature Review",
        "description": "Standalone literature review paper",
        "formats": {
            "systematic": "Systematic Literature Review (PRISMA): Introduction, Methods (search strategy, inclusion/exclusion criteria), Results (PRISMA flow, characteristics of studies, synthesis), Discussion, Conclusion, References.",
            "narrative": "Narrative Literature Review: Introduction, Thematic Sections, Discussion, Conclusion, References.",
            "scoping": "Scoping Review: Introduction, Methods (framework, search), Results (charting data), Discussion, Conclusion, References.",
            "bibliometric": "Bibliometric Review: Introduction, Data and Methods, Descriptive Results, Citation Analysis, Co-citation Analysis, Discussion, Conclusion, References.",
        },
    },
    "book_report": {
        "label": "Book Report",
        "description": "Analytical book report or review",
        "formats": {
            "analytical": "Analytical Book Report: Bibliographic Information, Introduction, Summary (chapter-by-chapter), Critical Analysis, Themes and Arguments, Strengths and Weaknesses, Conclusion, References.",
            "comparative": "Comparative Book Report: Introduction, Summary of Each Book, Comparative Analysis, Thematic Discussion, Conclusion, References.",
            "academic_review": "Academic Book Review: Bibliographic Info, Brief Summary, Critical Evaluation, Contribution to Field, Recommendation, References.",
        },
    },
    "review_paper": {
        "label": "Review Paper",
        "description": "Comprehensive review article for journal submission",
        "formats": {
            "Q1": "Top-tier review paper: Abstract, Introduction, Search Strategy, Thematic Analysis, Critical Synthesis, Research Agenda, Conclusion, References (100+).",
            "Q2": "Standard review paper: Abstract, Introduction, Literature Search, Thematic Review, Discussion, Future Directions, Conclusion, References (50-100).",
            "Q3": "Review paper: Abstract, Introduction, Literature Review, Discussion, Conclusion, References (30-50).",
            "narrative": "Narrative review: Abstract, Introduction, Background, Review Sections, Discussion, Conclusion, References.",
        },
    },
    "conference_paper": {
        "label": "Conference Paper",
        "description": "Paper for academic conference proceedings",
        "formats": {
            "full": "Full Conference Paper: Abstract, Introduction, Related Work, Methodology, Results, Discussion, Conclusion, References. Typically 8-12 pages.",
            "short": "Short Paper / Poster: Abstract, Introduction, Approach, Preliminary Results, Conclusion, References. Typically 4-6 pages.",
            "workshop": "Workshop Paper: Abstract, Introduction, Methodology, Results, Discussion, References. Typically 6-8 pages.",
        },
    },
    "research_proposal": {
        "label": "Research Proposal",
        "description": "Research proposal for funding or admission",
        "formats": {
            "grant": "Grant Proposal: Title, Abstract, Background and Significance, Specific Aims, Research Strategy (Preliminary Data, Approach), Timeline, Budget Justification, References.",
            "academic": "Academic Research Proposal: Title, Introduction, Literature Review, Research Questions, Methodology, Timeline, Expected Outcomes, References.",
            "phd_proposal": "PhD Research Proposal: Title, Introduction, Research Gap, Research Questions, Literature Review, Theoretical Framework, Methodology, Timeline, References. Typically 3,000-5,000 words.",
        },
    },
}


# ---------------------------------------------------------------------------
# Roadmap Template Definitions
# ---------------------------------------------------------------------------

def _get_research_article_roadmap(topic, fmt, field):
    """Generate roadmap for a research article."""
    fmt_desc = DOCUMENT_TYPES["research_article"]["formats"].get(fmt, DOCUMENT_TYPES["research_article"]["formats"]["general"])
    sections = [
        {"title": "Title Page", "purpose": "Concise, informative title; author names and affiliations; corresponding author email; keywords.", "est_words": 50, "guidelines": f"Title should be {('highly specific and novel for ' + fmt) if fmt == 'Q1' else 'clear and descriptive'}. Include 4-6 keywords relevant to {field}."},
        {"title": "Abstract", "purpose": "Self-contained summary of the entire paper: background, objective, methods, key results, and conclusion.", "est_words": 250, "guidelines": f"Structured abstract ({'250 words for ' + fmt if fmt in ('Q1','Q2') else '150-250 words'}). State the research gap, methodology, main findings, and implications for {field}."},
        {"title": "1. Introduction", "purpose": "Establish the research context, identify the knowledge gap, state objectives, and outline contributions.", "est_words": 1000, "guidelines": f"Start with broad context of {topic}, narrow to specific gap, state research questions, and list 3-4 contributions. {'For ' + fmt + ' journals, emphasize novelty and significance.' if fmt in ('Q1','Q2') else ''}"},
        {"title": "2. Literature Review", "purpose": "Synthesize prior research, identify gaps, and position your study within the field.", "est_words": 1500, "guidelines": f"Organize thematically (not chronologically). Cover {'comprehensive literature for ' + fmt if fmt == 'Q1' else 'key literature'}. Identify 3-5 research gaps. Connect to {field} theory."},
        {"title": "3. Methodology", "purpose": "Describe research design, data, variables, and analytical methods with enough detail for replication.", "est_words": 1200, "guidelines": f"Include: research design, data sources, sample description, variable definitions, model specification, identification strategy, and robustness checks. {'For ' + fmt + ' journals, justify all methodological choices with citations.' if fmt in ('Q1','Q2') else ''}"},
        {"title": "4. Results", "purpose": "Present empirical findings with tables, figures, and statistical evidence.", "est_words": 1500, "guidelines": f"Descriptive statistics first, then main results, then robustness checks. Use 3-5 tables and 2-4 figures. Report effect sizes and confidence intervals. {'For ' + fmt + ' journals, include heterogeneity analysis.' if fmt == 'Q1' else ''}"},
        {"title": "5. Discussion", "purpose": "Interpret results, compare with literature, discuss implications, and acknowledge limitations.", "est_words": 1000, "guidelines": f"Interpret findings in light of {topic} literature. Discuss theoretical and policy implications. Acknowledge 3-4 limitations and suggest future research directions."},
        {"title": "6. Conclusion", "purpose": "Summarize key findings, state contributions, and outline policy/practice implications.", "est_words": 500, "guidelines": f"Restate the research question, summarize 3-4 key findings, state contributions to {field}, and provide actionable recommendations."},
        {"title": "References", "purpose": "Complete list of cited works in the journal's required style.", "est_words": 0, "guidelines": f"{'50-100+ references for ' + fmt if fmt in ('Q1','Q2') else '30-60 references'}. Follow the target journal's citation style. Ensure all cited works are relevant and current."},
        {"title": "Appendices (Optional)", "purpose": "Supplementary materials, robustness tables, and mathematical proofs.", "est_words": 500, "guidelines": "Include additional robustness checks, variable definitions, or extended methodology details."},
    ]
    return sections, fmt_desc


def _get_thesis_roadmap(topic, fmt, field):
    """Generate roadmap for a thesis/dissertation."""
    fmt_desc = DOCUMENT_TYPES["thesis"]["formats"].get(fmt, "Standard thesis format.")
    is_chinese = "chinese" in fmt
    is_phd = "phd" in fmt
    is_undergrad = "undergraduate" in fmt

    if is_chinese:
        sections = [
            {"title": "摘要 (Abstract)", "purpose": "中英文摘要，概述研究背景、目的、方法、主要发现和结论。", "est_words": 500, "guidelines": f"中文摘要{'800-1500字' if is_phd else '500-800字'}，英文摘要{'500-1000词' if is_phd else '300-500词'}。关键词4-6个。"},
            {"title": "第一章 绪论 (Chapter 1: Introduction)", "purpose": "研究背景、研究问题、研究意义、研究目标、研究内容与技术路线。", "est_words": 3000 if is_phd else 1500, "guidelines": f"{'博士论文需要详细阐述研究创新点' if is_phd else '本科/硕士论文需要清晰说明研究价值'}。结合{field}领域背景。"},
            {"title": "第二章 文献综述 (Chapter 2: Literature Review)", "purpose": f"系统梳理{topic}相关文献，总结研究现状，识别研究空白。", "est_words": 6000 if is_phd else 3000, "guidelines": f"{'博士论文需综述100篇以上文献' if is_phd else '综述30-50篇文献'}。按主题组织，评述已有研究的贡献与不足。"},
            {"title": "第三章 理论框架 (Chapter 3: Theoretical Framework)", "purpose": "构建理论分析框架，提出研究假设。", "est_words": 4000 if is_phd else 2000, "guidelines": f"阐述理论基础，构建分析模型，提出{'3-5个研究假设' if is_phd else '2-3个研究假设'}。"},
            {"title": "第四章 研究方法 (Chapter 4: Methodology)", "purpose": "研究设计、数据来源、变量定义、模型设定。", "est_words": 4000 if is_phd else 2500, "guidelines": f"详细描述数据来源、样本选择、变量测量、计量模型。{'博士论文需说明识别策略' if is_phd else ''}"},
            {"title": "第五章 实证分析 (Chapter 5: Empirical Analysis)", "purpose": "描述性统计、基准回归结果、稳健性检验。", "est_words": 8000 if is_phd else 4000, "guidelines": f"{'博士论文需包含多个实证章节' if is_phd else '包含基准结果和稳健性检验'}。表格和图形要规范。"},
            {"title": "第六章 进一步分析 (Chapter 6: Further Analysis)", "purpose": "异质性分析、机制分析、扩展讨论。", "est_words": 5000 if is_phd else 0, "guidelines": "深入探讨作用机制、异质性效应。仅博士论文需要此章节。"} if is_phd else {"title": "(Optional) Further Analysis", "purpose": "Optional extended analysis section.", "est_words": 0, "guidelines": "Include if your study has additional analysis."},
            {"title": "第七章 结论与政策建议 (Chapter 7: Conclusion & Policy Implications)", "purpose": "总结主要发现，提出政策建议，讨论局限性和未来研究方向。", "est_words": 3000 if is_phd else 1500, "guidelines": f"总结{'5-7个' if is_phd else '3-4个'}主要发现，提出政策建议，承认研究局限。"},
            {"title": "参考文献 (References)", "purpose": "完整列出所有引用文献。", "est_words": 0, "guidelines": f"{'博士论文100-200篇参考文献' if is_phd else '硕士论文50-80篇' if not is_undergrad else '本科论文30-50篇'}。按照学校要求的格式。"},
            {"title": "致谢 (Acknowledgments)", "purpose": "感谢导师、家人、资助机构等。", "est_words": 300, "guidelines": "真诚感谢指导教师、评阅人、资助来源。"},
            {"title": "附录 (Appendices)", "purpose": "补充表格、数学推导、调查问卷等。", "est_words": 1000, "guidelines": "包含额外的稳健性检验结果、变量定义表等。"},
        ]
    elif "african" in fmt:
        degree_label = "PhD Thesis" if is_phd else "Master's Dissertation" if not is_undergrad else "Undergraduate Project"
        ref_count_label = "PhD: 150-250 references" if is_phd else "Master's: 60-100" if not is_undergrad else "Undergraduate: 30-50"
        sections = [
            {"title": "Title Page", "purpose": "Thesis title, author name, matriculation number, department, institution, month and year.", "est_words": 50, "guidelines": f"Follow your university's specific title page template. Include {degree_label} designation."},
            {"title": "Declaration", "purpose": "Statement of originality signed by the candidate.", "est_words": 100, "guidelines": "Standard declaration: 'I declare that this is my original work...'"},
            {"title": "Certification", "purpose": "Supervisor's certification and approval.", "est_words": 100, "guidelines": "Signed by supervisor with date. Include supervisor's name, title, and signature."},
            {"title": "Dedication", "purpose": "Personal dedication (optional).", "est_words": 50, "guidelines": "Brief personal dedication."},
            {"title": "Acknowledgments", "purpose": "Thank supervisor, family, funding bodies, and contributors.", "est_words": 300, "guidelines": "Acknowledge supervisor first, then department, funding, family."},
            {"title": "Abstract", "purpose": "Summary of the entire thesis.", "est_words": 350, "guidelines": f"{'300-500 words' if is_phd else '200-350 words'}. Cover background, objectives, methodology, findings, and contributions."},
            {"title": "Table of Contents", "purpose": "Complete listing of all sections, subsections, figures, tables, and abbreviations.", "est_words": 0, "guidelines": "Use automatic table of contents. Include List of Figures, List of Tables, List of Abbreviations."},
            {"title": "Chapter 1: Introduction", "purpose": f"Background to the study, statement of the problem, research questions, objectives, hypotheses, significance, scope and limitations, and organization of the thesis.", "est_words": 4000 if is_phd else 2500, "guidelines": f"{'PhD: comprehensive introduction with clear gap identification' if is_phd else 'Clear problem statement and objectives'}. Cover {field} context."},
            {"title": "Chapter 2: Literature Review", "purpose": f"Theoretical framework, conceptual framework, empirical review, and gap identification for {topic}.", "est_words": 8000 if is_phd else 5000, "guidelines": f"{'PhD: 100+ references, comprehensive theoretical and empirical review' if is_phd else '50+ references, solid review'}. Organize by themes."},
            {"title": "Chapter 3: Methodology", "purpose": "Research design, population and sample, data collection, analytical techniques, and model specification.", "est_words": 5000 if is_phd else 3000, "guidelines": f"Detail data sources, sampling technique, variables, and {'econometric models' if 'econ' in field.lower() else 'analytical methods'}. Justify all choices."},
            {"title": "Chapter 4: Results and Analysis", "purpose": f"Presentation of empirical findings for {topic}.", "est_words": 7000 if is_phd else 4000, "guidelines": "Descriptive statistics, correlation analysis, main regression results, and robustness checks. Use tables and figures."},
            {"title": "Chapter 5: Discussion of Findings", "purpose": "Interpretation and discussion of results in relation to literature.", "est_words": 5000 if is_phd else 3000, "guidelines": f"Compare findings with literature, discuss theoretical and {'policy' if 'african' in fmt else 'practical'} implications."},
            {"title": "Chapter 6: Summary, Conclusion and Recommendations", "purpose": "Summary of findings, conclusions, recommendations, and future research.", "est_words": 3000 if is_phd else 2000, "guidelines": f"Summarize {'5-7' if is_phd else '3-4'} key findings, provide policy recommendations, acknowledge limitations."},
            {"title": "References", "purpose": "Complete reference list.", "est_words": 0, "guidelines": f"{ref_count_label}. Follow APA or university-specified style."},
            {"title": "Appendices", "purpose": "Supplementary materials.", "est_words": 1000, "guidelines": "Questionnaires, additional tables, mathematical proofs, and data descriptions."},
        ]
    else:
        # USA / UK / European format
        sections = [
            {"title": "Title Page", "purpose": "Thesis title, author, institution, department, degree, date.", "est_words": 50, "guidelines": f"Follow {'university' if is_undergrad else 'graduate school'} formatting requirements."},
            {"title": "Abstract", "purpose": "Comprehensive summary of the thesis.", "est_words": 350 if is_phd else 250, "guidelines": f"{'PhD: 350 words (UK 1,000-word structured abstract)' if is_phd else '250-350 words'}. Cover all chapters."},
            {"title": "Acknowledgments", "purpose": "Thank advisors, committee, funders, and family.", "est_words": 300, "guidelines": "Professional and sincere. Acknowledge funding sources."},
            {"title": "Table of Contents", "purpose": "Complete chapter and section listing.", "est_words": 0, "guidelines": "Auto-generated. Include List of Tables, List of Figures."},
            {"title": "Chapter 1: Introduction", "purpose": f"Background, motivation, research questions, contributions, and roadmap for {topic}.", "est_words": 5000 if is_phd else 3000 if not is_undergrad else 2000, "guidelines": f"{'PhD: detailed introduction with clear research gap and significance' if is_phd else 'Clear motivation and research questions'}. Position within {field}."},
            {"title": "Chapter 2: Literature Review", "purpose": f"Comprehensive synthesis of existing research on {topic}.", "est_words": 10000 if is_phd else 5000 if not is_undergrad else 3000, "guidelines": f"{'PhD: 100-200+ references, theoretical and empirical review' if is_phd else '50-80 references'}. Identify gaps your thesis addresses."},
            {"title": "Chapter 3: Theoretical Framework", "purpose": "Theoretical foundations and hypothesis development.", "est_words": 5000 if is_phd else 3000, "guidelines": f"{'PhD: original theoretical contribution expected' if is_phd else 'Clear theoretical framework'}. Develop {'5-8' if is_phd else '3-5'} testable hypotheses."},
            {"title": "Chapter 4: Methodology", "purpose": "Research design, data, variables, and methods.", "est_words": 6000 if is_phd else 4000, "guidelines": f"Detail data sources, sample, variables, {'and identification strategy' if is_phd else 'and model specification'}. {'European format: include research paradigm justification.' if 'european' in fmt else ''}"},
            {"title": "Chapter 5: Results", "purpose": f"Empirical findings for {topic}.", "est_words": 8000 if is_phd else 5000, "guidelines": f"{'PhD: multiple results chapters possible' if is_phd else 'Single results chapter'}. Descriptive stats, main results, robustness."},
            {"title": "Chapter 6: Discussion", "purpose": "Interpretation and synthesis of findings.", "est_words": 6000 if is_phd else 4000, "guidelines": f"{'PhD: extensive discussion connecting to theory' if is_phd else 'Clear discussion of findings'}. Theoretical and practical implications."},
            {"title": "Chapter 7: Conclusion", "purpose": "Summary, contributions, limitations, and future research.", "est_words": 4000 if is_phd else 2500, "guidelines": f"Summarize {'6-8' if is_phd else '3-5'} key findings, state contributions to {field}, and outline future research."},
            {"title": "References", "purpose": "Complete reference list.", "est_words": 0, "guidelines": f"{'PhD: 150-300 references' if is_phd else '60-100' if not is_undergrad else '30-50'}. {'UK: use Bibliography heading' if 'uk' in fmt else 'Use References heading'}. Follow required style."},
            {"title": "Appendices", "purpose": "Supplementary materials.", "est_words": 2000, "guidelines": "Additional tables, proofs, survey instruments, and data descriptions."},
        ]
    return sections, fmt_desc


def _get_literature_review_roadmap(topic, fmt, field):
    fmt_desc = DOCUMENT_TYPES["literature_review"]["formats"].get(fmt, DOCUMENT_TYPES["literature_review"]["formats"]["narrative"])
    sections = [
        {"title": "Abstract", "purpose": "Summary of the review's scope, methodology, and key findings.", "est_words": 250, "guidelines": f"{'For systematic reviews: state search strategy, number of included studies, and main synthesis findings' if fmt == 'systematic' else 'State the review scope, themes identified, and key conclusions'}."},
        {"title": "1. Introduction", "purpose": f"Establish the importance of {topic}, define scope, and state review objectives.", "est_words": 800, "guidelines": f"Explain why {topic} deserves a review. {'For systematic reviews: state PICO/SPIDER framework' if fmt == 'systematic' else 'Define the review scope and boundaries'}."},
        {"title": "2. Methods", "purpose": "Describe the search strategy, inclusion/exclusion criteria, and synthesis approach.", "est_words": 1000 if fmt in ("systematic", "scoping", "bibliometric") else 300, "guidelines": f"{'PRISMA guidelines for systematic reviews: databases, search terms, screening process, quality assessment' if fmt == 'systematic' else 'For bibliometric: data source, software (VOSviewer/CiteSpace), analysis methods' if fmt == 'bibliometric' else 'Brief description of literature search approach'}."},
        {"title": "3. Thematic Analysis", "purpose": "Organize and synthesize literature by themes.", "est_words": 3000, "guidelines": f"Identify 4-6 major themes in {topic} literature. For each theme: synthesize findings, compare approaches, and identify consensus/disagreement."},
        {"title": "4. Critical Synthesis", "purpose": "Evaluate the quality, consistency, and gaps in the literature.", "est_words": 1500, "guidelines": "Assess methodological quality across studies. Identify contradictory findings and possible explanations. Highlight under-researched areas."},
        {"title": "5. Research Agenda", "purpose": "Propose future research directions based on identified gaps.", "est_words": 800, "guidelines": f"List 5-8 specific research questions that need investigation in {topic}. Categorize as theoretical, methodological, and empirical gaps."},
        {"title": "6. Conclusion", "purpose": "Summarize key insights from the review.", "est_words": 500, "guidelines": "Restate the review's contribution, summarize 3-4 key findings, and state the significance for the field."},
        {"title": "References", "purpose": "Complete reference list.", "est_words": 0, "guidelines": f"{'80-150+ references for systematic/bibliometric reviews' if fmt in ('systematic', 'bibliometric') else '50-80 references'}. Follow target journal style."},
    ]
    return sections, fmt_desc


def _get_book_report_roadmap(topic, fmt, field):
    fmt_desc = DOCUMENT_TYPES["book_report"]["formats"].get(fmt, DOCUMENT_TYPES["book_report"]["formats"]["analytical"])
    sections = [
        {"title": "Bibliographic Information", "purpose": "Full citation of the book.", "est_words": 50, "guidelines": "Author, title, publisher, year, ISBN, pages."},
        {"title": "1. Introduction", "purpose": f"Introduce the book and its relevance to {field}.", "est_words": 400, "guidelines": f"State the book's main thesis and your overall assessment. Explain why {topic} is important."},
        {"title": "2. Summary of Content", "purpose": "Chapter-by-chapter summary of the book.", "est_words": 1000, "guidelines": "Provide a structured summary organized by chapter or major section. Do not critique yet—just summarize."},
        {"title": "3. Critical Analysis", "purpose": "Evaluate the book's arguments, evidence, and methodology.", "est_words": 1500, "guidelines": f"Assess the author's arguments, use of evidence, methodology, and {'comparative analysis if multiple books' if fmt == 'comparative' else 'analytical depth'}. Discuss strengths and weaknesses."},
        {"title": "4. Themes and Arguments", "purpose": "Identify and discuss the major themes.", "est_words": 800, "guidelines": f"Identify 3-4 major themes in the book. Discuss how they relate to {field} and {topic}."},
        {"title": "5. Strengths and Weaknesses", "purpose": "Balanced evaluation of the book's contributions and limitations.", "est_words": 600, "guidelines": "Discuss 2-3 specific strengths and 2-3 weaknesses with examples from the text."},
        {"title": "6. Conclusion", "purpose": "Final assessment and recommendation.", "est_words": 400, "guidelines": f"State your overall assessment. Who would benefit from reading this book? How does it contribute to {field}?"},
        {"title": "References", "purpose": "Additional sources cited in the report.", "est_words": 0, "guidelines": "Include any additional sources used in your analysis."},
    ]
    return sections, fmt_desc


def _get_review_paper_roadmap(topic, fmt, field):
    fmt_desc = DOCUMENT_TYPES["review_paper"]["formats"].get(fmt, DOCUMENT_TYPES["review_paper"]["formats"]["narrative"])
    sections = [
        {"title": "Abstract", "purpose": "Structured abstract summarizing the review.", "est_words": 250, "guidelines": f"{'For Q1 reviews: structured abstract with background, objective, methods, findings, and conclusions' if fmt == 'Q1' else 'State the review scope and key findings'}."},
        {"title": "1. Introduction", "purpose": f"Establish the significance of {topic} and the need for a review.", "est_words": 1200, "guidelines": f"{'For Q1: emphasize the gap this review fills and its significance to the field' if fmt == 'Q1' else 'Explain why a review is needed now'}. State the review's scope and objectives."},
        {"title": "2. Search Strategy", "purpose": "Describe how literature was identified and selected.", "est_words": 800, "guidelines": f"{'For Q1/Q2: formal search strategy with databases, keywords, and inclusion criteria' if fmt in ('Q1', 'Q2') else 'Brief description of literature search'}."},
        {"title": "3. Background and Context", "purpose": "Provide theoretical and historical context.", "est_words": 1500, "guidelines": f"Trace the development of {topic} in {field}. Define key concepts and theories."},
        {"title": "4. Thematic Review", "purpose": "Organized synthesis of literature by themes.", "est_words": 4000, "guidelines": f"Identify {'6-8' if fmt == 'Q1' else '4-6'} themes. For each: synthesize findings, evaluate methods, and identify gaps."},
        {"title": "5. Critical Synthesis", "purpose": "Cross-cutting analysis and gap identification.", "est_words": 2000, "guidelines": f"{'For Q1: rigorous critical analysis of methodological quality and theoretical contributions' if fmt == 'Q1' else 'Assess the overall state of the field'}. Identify contradictions and unresolved debates."},
        {"title": "6. Research Agenda", "purpose": "Future research directions.", "est_words": 1000, "guidelines": f"{'For Q1: detailed research agenda with specific questions and methodological recommendations' if fmt == 'Q1' else 'List 5-8 future research directions'}."},
        {"title": "7. Conclusion", "purpose": "Summary of the review's contributions.", "est_words": 500, "guidelines": f"Summarize key insights, state the review's contribution to {field}, and highlight the most pressing research gap."},
        {"title": "References", "purpose": "Complete reference list.", "est_words": 0, "guidelines": f"{'Q1: 100-200+ references' if fmt == 'Q1' else 'Q2: 50-100' if fmt == 'Q2' else '30-60 references'}. Follow target journal style."},
    ]
    return sections, fmt_desc


def _get_conference_paper_roadmap(topic, fmt, field):
    fmt_desc = DOCUMENT_TYPES["conference_paper"]["formats"].get(fmt, DOCUMENT_TYPES["conference_paper"]["formats"]["full"])
    sections = [
        {"title": "Abstract", "purpose": "Concise summary of the paper.", "est_words": 200, "guidelines": f"{'Full paper: 200-250 words' if fmt == 'full' else 'Short paper: 150 words'}. State problem, approach, and key results."},
        {"title": "1. Introduction", "purpose": f"Motivate the research on {topic} and state contributions.", "est_words": 800 if fmt == "full" else 400, "guidelines": f"{'Full paper: detailed introduction with related work' if fmt == 'full' else 'Short paper: brief introduction'}. List 2-3 contributions."},
        {"title": "2. Related Work", "purpose": "Position the work within existing literature.", "est_words": 500 if fmt == "full" else 200, "guidelines": f"{'Full paper: comprehensive related work section' if fmt == 'full' else 'Brief mention of closest work'}. Differentiate your contribution."},
        {"title": "3. Methodology", "purpose": "Describe the research approach.", "est_words": 1000 if fmt == "full" else 500, "guidelines": f"Detail the approach for studying {topic}. Include data and methods."},
        {"title": "4. Results", "purpose": "Present findings.", "est_words": 1000 if fmt == "full" else 500, "guidelines": "Present key results with tables and figures. Keep concise for conference format."},
        {"title": "5. Discussion and Conclusion", "purpose": "Interpret results and state conclusions.", "est_words": 500 if fmt == "full" else 300, "guidelines": f"Discuss implications for {field} and future work."},
        {"title": "References", "purpose": "Reference list.", "est_words": 0, "guidelines": f"{'Full paper: 20-40 references' if fmt == 'full' else '10-20 references'}. Follow conference style."},
    ]
    return sections, fmt_desc


def _get_research_proposal_roadmap(topic, fmt, field):
    fmt_desc = DOCUMENT_TYPES["research_proposal"]["formats"].get(fmt, DOCUMENT_TYPES["research_proposal"]["formats"]["academic"])
    sections = [
        {"title": "Title", "purpose": "Concise, descriptive title.", "est_words": 20, "guidelines": f"Title should capture the essence of {topic} and the research approach."},
        {"title": "1. Abstract / Executive Summary", "purpose": "Brief overview of the proposed research.", "est_words": 300, "guidelines": f"{'Grant: emphasize significance and innovation' if fmt == 'grant' else 'Academic: emphasize research gap and approach'}."},
        {"title": "2. Background and Significance", "purpose": f"Establish the context and importance of {topic}.", "est_words": 1000, "guidelines": f"Explain the problem, its significance to {field}, and the gap your research addresses."},
        {"title": "3. Literature Review", "purpose": "Synthesize relevant literature.", "est_words": 1500, "guidelines": f"{'Grant: focused on gap and innovation' if fmt == 'grant' else 'Comprehensive review'}. Identify the gap your research fills."},
        {"title": "4. Research Questions / Specific Aims", "purpose": "State clear, testable research questions.", "est_words": 400, "guidelines": f"{'Grant: 2-4 specific aims' if fmt == 'grant' else '3-5 research questions'}. Make them specific and measurable."},
        {"title": "5. Theoretical Framework", "purpose": "Theoretical foundation for the research.", "est_words": 800, "guidelines": f"Present the theoretical lens through which {topic} will be studied. Develop hypotheses."},
        {"title": "6. Methodology", "purpose": "Detailed research design and methods.", "est_words": 1500, "guidelines": f"Describe data, sample, variables, {'and identification strategy' if fmt == 'grant' else 'and analytical methods'}. {'Grant: include preliminary data' if fmt == 'grant' else ''}"},
        {"title": "7. Timeline", "purpose": "Research schedule.", "est_words": 200, "guidelines": f"{'Grant: detailed timeline with milestones' if fmt == 'grant' else 'Gantt chart or milestone table'}. Typically {'3-5 years for grant' if fmt == 'grant' else '1-3 years for PhD' if fmt == 'phd_proposal' else '6-12 months'}."},
        {"title": "8. Expected Outcomes and Impact", "purpose": "Anticipated results and significance.", "est_words": 400, "guidelines": f"Describe expected findings, their contribution to {field}, and broader impact."},
        {"title": "9. Budget Justification", "purpose": "Research budget.", "est_words": 300 if fmt == "grant" else 0, "guidelines": "Grant proposals: detailed budget with justification for each item."} if fmt == "grant" else {"title": "(Optional) Budget", "purpose": "Research budget if applicable.", "est_words": 0, "guidelines": "Include if funding is requested."},
        {"title": "References", "purpose": "Reference list.", "est_words": 0, "guidelines": f"{'Grant: 30-60 references' if fmt == 'grant' else '50-80 references'}. Follow required style."},
    ]
    return sections, fmt_desc


ROADMAP_GENERATORS = {
    "research_article": _get_research_article_roadmap,
    "thesis": _get_thesis_roadmap,
    "literature_review": _get_literature_review_roadmap,
    "book_report": _get_book_report_roadmap,
    "review_paper": _get_review_paper_roadmap,
    "conference_paper": _get_conference_paper_roadmap,
    "research_proposal": _get_research_proposal_roadmap,
}


# ---------------------------------------------------------------------------
# Topic Suggestion Engine
# ---------------------------------------------------------------------------

# Research fields with their sub-areas and trending topics
RESEARCH_FIELDS = {
    "economics": {
        "label": "Economics & Finance",
        "sub_areas": [
            "Macroeconomics", "Microeconomics", "Development Economics", "International Economics",
            "Financial Economics", "Behavioral Economics", "Labor Economics", "Environmental Economics",
            "Public Economics", "Econometrics", "Monetary Economics", "Trade Economics",
        ],
        "trending_gaps": [
            "Climate finance and green bond effectiveness in emerging markets",
            "Digital currency adoption and monetary policy transmission",
            "AI-driven labor market disruption in developing economies",
            "Geopolitical fragmentation and global value chain restructuring",
            "Inflation dynamics in post-pandemic African economies",
            "FDI crowding-in/out effects in Mano River Union countries",
            "Institutional quality thresholds for economic convergence",
            "Cryptocurrency regulation and financial stability in Africa",
            "Trade openness and industrialization in ECOWAS region",
            "Remittance channels and household welfare in conflict zones",
        ],
    },
    "political_science": {
        "label": "Political Science & International Relations",
        "sub_areas": [
            "Comparative Politics", "International Relations", "Political Theory",
            "Public Policy", "Conflict Resolution", "Democratization",
            "Governance", "Security Studies",
        ],
        "trending_gaps": [
            "Democratic backsliding and electoral integrity in West Africa",
            "Social media regulation and political polarization",
            "Climate-induced migration and interstate conflict",
            "AU-ECOWAS conflict prevention effectiveness",
            "Cyber warfare and international law gaps",
            "Post-conflict reconstruction and institutional trust",
            "China-Africa relations and sovereignty implications",
            "Youth political participation in fragile states",
        ],
    },
    "sociology": {
        "label": "Sociology & Social Sciences",
        "sub_areas": [
            "Social Stratification", "Urban Sociology", "Rural Sociology",
            "Sociology of Education", "Medical Sociology", "Environmental Sociology",
            "Sociology of Religion", "Gender Studies",
        ],
        "trending_gaps": [
            "Digital divide and social inequality in post-COVID societies",
            "Climate displacement and community resilience",
            "Gig economy and worker identity formation",
            "Social capital and mental health in urban Africa",
            "Intergenerational mobility in resource-dependent economies",
            "Social media and youth civic engagement",
            "Traditional justice systems and social cohesion",
        ],
    },
    "public_health": {
        "label": "Public Health & Medicine",
        "sub_areas": [
            "Epidemiology", "Health Policy", "Global Health", "Health Economics",
            "Environmental Health", "Maternal & Child Health", "Infectious Diseases",
            "Health Equity", "Mental Health",
        ],
        "trending_gaps": [
            "Post-pandemic health system resilience in LMICs",
            "Mental health burden of climate-related displacement",
            "AI-assisted diagnosis in resource-limited settings",
            "Vaccine hesitancy and health communication strategies",
            "One Health approach to zoonotic disease surveillance",
            "Universal health coverage financing in West Africa",
            "Maternal mortality disparities in conflict-affected regions",
            "Antimicrobial resistance in informal healthcare markets",
        ],
    },
    "environment": {
        "label": "Environmental Science & Climate",
        "sub_areas": [
            "Climate Change", "Conservation Biology", "Environmental Policy",
            "Sustainable Development", "Water Resources", "Renewable Energy",
            "Pollution Control", "Biodiversity",
        ],
        "trending_gaps": [
            "Nature-based solutions for urban flood resilience",
            "Blue carbon potential of West African mangroves",
            "Climate adaptation finance gaps in Sub-Saharan Africa",
            "Renewable energy transition and mineral supply chains",
            "Deforestation drivers and REDD+ effectiveness",
            "Plastic pollution in freshwater systems",
            "Climate-smart agriculture adoption barriers",
            "Environmental migration patterns in the Sahel",
        ],
    },
    "education": {
        "label": "Education & Pedagogy",
        "sub_areas": [
            "Educational Leadership", "Curriculum Development", "Educational Technology",
            "Higher Education", "Special Education", "Comparative Education",
            "Teacher Education", "Assessment & Evaluation",
        ],
        "trending_gaps": [
            "AI integration in African higher education curricula",
            "Post-COVID learning loss recovery strategies",
            "Mother-tongue instruction and learning outcomes",
            "Teacher motivation and retention in rural schools",
            "Open educational resources and equity in access",
            "Competency-based education implementation challenges",
            "Digital assessment integrity in online learning",
            "STEM gender gap in Sub-Saharan African universities",
        ],
    },
    "technology": {
        "label": "Computer Science & Technology",
        "sub_areas": [
            "Artificial Intelligence", "Data Science", "Cybersecurity",
            "Software Engineering", "Human-Computer Interaction", "IoT",
            "Blockchain", "Cloud Computing", "Machine Learning",
        ],
        "trending_gaps": [
            "Federated learning for privacy-preserving healthcare AI",
            "Blockchain for land tenure security in West Africa",
            "Low-resource NLP for African languages",
            "Edge AI for agricultural pest detection",
            "Cybersecurity governance in developing nations",
            "AI ethics frameworks for Global South contexts",
            "Digital identity systems and privacy rights",
            "Quantum-resistant cryptography migration strategies",
        ],
    },
    "law": {
        "label": "Law & Legal Studies",
        "sub_areas": [
            "Constitutional Law", "International Law", "Human Rights Law",
            "Commercial Law", "Environmental Law", "Criminal Justice",
            "Intellectual Property", "Comparative Law",
        ],
        "trending_gaps": [
            "AI governance and liability frameworks",
            "Customary law and formal legal system integration in Africa",
            "Climate litigation and human rights",
            "Data protection regulation in ECOWAS",
            "Corporate accountability for environmental damage",
            "Refugee rights and climate displacement law",
            "Digital copyright and fair use in the AI era",
            "Land rights and extractive industry governance",
        ],
    },
    "business": {
        "label": "Business & Management",
        "sub_areas": [
            "Strategic Management", "Entrepreneurship", "International Business",
            "Marketing", "Organizational Behavior", "Supply Chain Management",
            "Corporate Governance", "Innovation Management",
        ],
        "trending_gaps": [
            "Digital transformation in African SMEs",
            "ESG reporting and firm performance in emerging markets",
            "Social entrepreneurship and poverty reduction",
            "Supply chain resilience post-COVID",
            "Women-owned businesses and access to finance",
            "Informal sector formalization incentives",
            "Remote work and organizational culture",
            "Fintech adoption and financial inclusion",
        ],
    },
    "agriculture": {
        "label": "Agriculture & Food Science",
        "sub_areas": [
            "Agronomy", "Food Security", "Agricultural Economics",
            "Animal Science", "Plant Breeding", "Soil Science",
            "Agricultural Extension", "Food Technology",
        ],
        "trending_gaps": [
            "Regenerative agriculture and carbon sequestration",
            "Post-harvest loss reduction technologies",
            "Urban agriculture and food security",
            "Drought-tolerant crop varieties adoption",
            "Digital agriculture and smallholder farmers",
            "Food safety in informal markets",
            "Aquaculture sustainability in West Africa",
            "Agricultural insurance and climate risk",
        ],
    },
    "interdisciplinary": {
        "label": "Interdisciplinary & Emerging Fields",
        "sub_areas": [
            "Data Ethics", "Science & Technology Studies", "Digital Humanities",
            "Complexity Science", "Sustainability Science", "Global Studies",
            "Disaster Studies", "Peace Studies",
        ],
        "trending_gaps": [
            "AI-human collaboration frameworks across disciplines",
            "Climate-conflict-migration nexus modeling",
            "Digital colonialism and data sovereignty",
            "Planetary health as an integrative framework",
            "Post-growth economics and well-being indicators",
            "Open science practices in Global South research",
            "Decolonizing knowledge production",
            "Resilience thinking in social-ecological systems",
        ],
    },
}


def suggest_research_topics(field: str, keywords: str = "", focus_novelty: bool = True, max_topics: int = 10) -> dict:
    """Generate research topic suggestions with novelty analysis."""
    field_key = field.lower().replace(" ", "_")
    field_data = RESEARCH_FIELDS.get(field_key, RESEARCH_FIELDS["interdisciplinary"])

    # Base topics from the field's trending gaps
    topics = list(field_data["trending_gaps"])

    # If keywords provided, generate topic variations
    if keywords:
        kw_list = [k.strip() for k in keywords.split(",") if k.strip()]
        for kw in kw_list[:3]:
            for sub_area in field_data["sub_areas"][:4]:
                topics.append(f"The role of {kw} in {sub_area.lower()} within {field_data['label'].lower()}")

    # Add sub-area-based topics
    for sub in field_data["sub_areas"]:
        topics.append(f"Unexplored determinants of outcomes in {sub.lower()}: evidence from developing contexts")

    # Deduplicate and limit
    seen = set()
    unique_topics = []
    for t in topics:
        key = t.lower()[:60]
        if key not in seen:
            seen.add(key)
            unique_topics.append(t)

    # Build structured suggestions with novelty analysis
    suggestions = []
    for i, topic in enumerate(unique_topics[:max_topics]):
        # Determine novelty factors
        novelty_factors = []
        if "Africa" in topic or "African" in topic or "ECOWAS" in topic or "Sahel" in topic or "Mano River" in topic:
            novelty_factors.append("Geographic focus on under-researched African context")
        if "AI" in topic or "digital" in topic.lower() or "blockchain" in topic.lower() or "cryptocurrency" in topic.lower():
            novelty_factors.append("Addresses emerging technology with limited empirical evidence")
        if "post-COVID" in topic or "post-pandemic" in topic:
            novelty_factors.append("Novel post-pandemic empirical context")
        if "climate" in topic.lower():
            novelty_factors.append("Climate-related research gap with policy urgency")
        if "informal" in topic.lower():
            novelty_factors.append("Focus on informal sector, often overlooked in mainstream research")
        if not novelty_factors:
            novelty_factors.append("Under-explored intersection with limited existing literature")

        # Suggest methodology
        methodologies = []
        if "effectiveness" in topic.lower() or "impact" in topic.lower():
            methodologies.append("Difference-in-Differences or IV/2SLS for causal identification")
        if "adoption" in topic.lower() or "barriers" in topic.lower():
            methodologies.append("Mixed methods: survey + econometric analysis")
        if "dynamics" in topic.lower() or "patterns" in topic.lower():
            methodologies.append("Panel data with fixed effects")
        if "relationship" in topic.lower() or "role" in topic.lower():
            methodologies.append("OLS/Panel regression with robustness checks")
        if not methodologies:
            methodologies.append("Quantitative analysis with panel/cross-sectional data")

        suggestions.append({
            "topic": topic,
            "field": field_data["label"],
            "sub_area": field_data["sub_areas"][i % len(field_data["sub_areas"])],
            "novelty_factors": novelty_factors,
            "suggested_methodology": methodologies,
            "research_gap": f"This topic addresses a gap in {field_data['label'].lower()} where {' '.join(novelty_factors[:2])}.",
            "estimated_difficulty": "High" if "AI" in topic or "blockchain" in topic.lower() else "Medium",
            "potential_journals": _suggest_journals(field_key, topic),
        })

    return {
        "field": field_data["label"],
        "sub_areas": field_data["sub_areas"],
        "topics": suggestions,
        "total": len(suggestions),
        "note": "Topics are generated based on current research gaps and trending issues. Verify novelty through literature search before proceeding." if focus_novelty else "Topics span major and minor issues in the field.",
    }


def _suggest_journals(field_key, topic):
    """Suggest potential target journals based on field and topic."""
    journal_map = {
        "economics": ["Economic Systems", "Journal of Development Economics", "World Development", "Journal of African Economies", "Economics Letters"],
        "political_science": ["Journal of Democracy", "African Affairs", "Journal of Modern African Studies", "Political Studies"],
        "sociology": ["Sociology", "African Sociological Review", "Journal of Development Studies", "Social Forces"],
        "public_health": ["Lancet Global Health", "BMC Public Health", "African Journal of Health Sciences", "Global Health Action"],
        "environment": ["Environmental Science & Policy", "Climate and Development", "Journal of Environmental Management", "Sustainability"],
        "education": ["Compare", "International Journal of Educational Development", "African Journal of Teacher Education"],
        "technology": ["IEEE Access", "ACM Computing Surveys", "Electronic Journal of Information Systems in Developing Countries"],
        "law": ["African Journal of International and Comparative Law", "Journal of African Law", "International Environmental Agreements"],
        "business": ["Journal of African Business", "International Journal of Emerging Markets", "Technological Forecasting and Social Change"],
        "agriculture": ["Food Policy", "Agricultural Economics", "Journal of Agricultural Economics", "Food Security"],
        "interdisciplinary": ["World Development", "Sustainability Science", "Journal of International Development", "Global Environmental Change"],
    }
    return journal_map.get(field_key, ["World Development", "Journal of International Development"])


# ---------------------------------------------------------------------------
# Open Access Article Finder
# Searches: OpenAlex (240M+) + Semantic Scholar (200M+) + CORE (200M+)
#           + DOAJ (6M+) + arXiv (2.4M+) + Crossref OA (150M+)
#           + Academia.edu (47M+) link provider
# Combined access: 300M+ unique papers across all research fields
# ---------------------------------------------------------------------------

# List of all sources for UI display
OA_SOURCES = [
    {"id": "openalex", "name": "OpenAlex", "papers": "240M+", "note": "Global research works"},
    {"id": "semantic_scholar", "name": "Semantic Scholar", "papers": "200M+", "note": "AI-powered paper search"},
    {"id": "core", "name": "CORE", "papers": "200M+", "note": "Open access repositories"},
    {"id": "crossref", "name": "Crossref", "papers": "150M+", "note": "DOI registry"},
    {"id": "doaj", "name": "DOAJ", "papers": "6M+", "note": "Open access journals"},
    {"id": "arxiv", "name": "arXiv", "papers": "2.4M+", "note": "Preprints (STEM)"},
    {"id": "academia_edu", "name": "Academia.edu", "papers": "47M+", "note": "Academic papers platform"},
]


async def find_open_access_articles(topic: str, max_results: int = 15) -> dict:
    """Search for open access articles across multiple sources.

    Aggregates results from OpenAlex, Semantic Scholar, CORE, DOAJ, arXiv,
    Crossref (OA filter), and Academia.edu to provide access to 300M+ papers.
    """
    articles = []

    async with httpx.AsyncClient(
        timeout=45.0,
        headers={"User-Agent": PLATFORM_UA},
        follow_redirects=True,
    ) as client:
        tasks = [
            _search_openalex_oa(topic, max_results, client),
            _search_s2_oa(topic, max_results, client),
            _search_core_oa(topic, max_results, client),
            _search_doaj_oa(topic, max_results, client),
            _search_arxiv_oa(topic, max_results, client),
            _search_crossref_oa(topic, max_results, client),
            _search_academia_edu(topic, max_results, client),
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)

    # Track which sources returned results
    sources_searched = []
    sources_succeeded = []
    source_names = ["OpenAlex", "Semantic Scholar", "CORE", "DOAJ", "arXiv", "Crossref", "Academia.edu"]
    for i, result in enumerate(results):
        source_name = source_names[i] if i < len(source_names) else f"Source_{i}"
        sources_searched.append(source_name)
        if isinstance(result, Exception):
            print(f"[OA {source_name}] Exception: {result}")
            continue
        if isinstance(result, list) and len(result) > 0:
            sources_succeeded.append(source_name)
            articles.extend(result)

    # Deduplicate by DOI or title
    seen = set()
    unique = []
    for a in articles:
        key = a.get("doi", "").lower() if a.get("doi") else a.get("title", "").lower()[:80]
        if key and key not in seen:
            seen.add(key)
            unique.append(a)

    # Sort by citation count (fall back to year for ties)
    unique.sort(key=lambda x: (x.get("cited_by_count", 0), x.get("year") or 0), reverse=True)
    unique = unique[:max_results]

    return {
        "topic": topic,
        "total_found": len(unique),
        "articles": unique,
        "sources_searched": sources_searched,
        "sources_succeeded": sources_succeeded,
        "search_timestamp": datetime.now(timezone.utc).isoformat(),
    }


# ---------------------------------------------------------------------------
# Source 1: OpenAlex (240M+ works)
# ---------------------------------------------------------------------------

async def _search_openalex_oa(query, max_results, client):
    """Search OpenAlex for open access works with PDF URLs."""
    params = {
        "search": query,
        "per-page": min(max_results * 3, 75),
        "mailto": CONTACT_EMAIL,
        "filter": "is_oa:true",
    }
    try:
        resp = await client.get("https://api.openalex.org/works", params=params)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print(f"[OA OpenAlex] Error: {e}")
        return []

    articles = []
    for work in data.get("results", []):
        best_oa = work.get("best_oa_location", {}) or {}
        pdf_url = best_oa.get("pdf_url")

        if not pdf_url:
            primary_loc = work.get("primary_location", {}) or {}
            pdf_url = primary_loc.get("pdf_url")

        if not pdf_url:
            for loc in work.get("locations", []) or []:
                loc_pdf = loc.get("pdf_url")
                if loc_pdf:
                    pdf_url = loc_pdf
                    break

        if not pdf_url:
            continue

        landing_url = best_oa.get("landing_page_url") or pdf_url

        authors = []
        for auth in work.get("authorships", [])[:5]:
            name = auth.get("author", {}).get("display_name", "")
            if name:
                authors.append(name)

        articles.append({
            "title": work.get("display_name", ""),
            "authors": authors,
            "year": work.get("publication_year"),
            "journal": (work.get("primary_location", {}) or {}).get("source", {}).get("display_name", ""),
            "doi": work.get("doi", ""),
            "abstract": _reconstruct_abstract(work.get("abstract_inverted_index")),
            "cited_by_count": work.get("cited_by_count", 0),
            "is_open_access": True,
            "pdf_url": pdf_url,
            "oa_url": landing_url,
            "source": "OpenAlex",
            "openalex_id": work.get("id", ""),
            "license": best_oa.get("license", ""),
        })
    return articles


# ---------------------------------------------------------------------------
# Source 2: Semantic Scholar (200M+ papers)
# ---------------------------------------------------------------------------

async def _search_s2_oa(query, max_results, client):
    """Search Semantic Scholar for open access papers."""
    params = {
        "query": query,
        "limit": min(max_results * 2, 50),
        "fields": "title,abstract,authors,year,citationCount,journal,externalIds,openAccessPdf",
    }
    try:
        resp = await client.get(
            "https://api.semanticscholar.org/graph/v1/paper/search",
            params=params,
        )
        if resp.status_code == 429:
            print("[OA S2] Rate limited (429). Returning empty.")
            return []
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print(f"[OA S2] Error: {e}")
        return []

    articles = []
    for item in data.get("data", []):
        oa_pdf = item.get("openAccessPdf", {}) or {}
        pdf_url = oa_pdf.get("url")
        if not pdf_url:
            continue

        authors = [a.get("name", "") for a in item.get("authors", [])[:5] if a.get("name")]
        ext_ids = item.get("externalIds", {}) or {}

        articles.append({
            "title": item.get("title", ""),
            "authors": authors,
            "year": item.get("year"),
            "journal": (item.get("journal", {}) or {}).get("name", ""),
            "doi": ext_ids.get("DOI", ""),
            "abstract": item.get("abstract"),
            "cited_by_count": item.get("citationCount", 0),
            "is_open_access": True,
            "pdf_url": pdf_url,
            "oa_url": pdf_url,
            "source": "Semantic Scholar",
        })
    return articles


# ---------------------------------------------------------------------------
# Source 3: CORE (200M+ papers from repositories worldwide)
# ---------------------------------------------------------------------------

async def _search_core_oa(query, max_results, client):
    """Search CORE for open access research papers."""
    # CORE v3 API - uses query parameter
    params = {
        "q": query,
        "limit": min(max_results * 2, 50),
    }
    headers = {"User-Agent": PLATFORM_UA}
    try:
        resp = await client.post(
            "https://api.core.ac.uk/v3/search/works",
            json=params,
            headers=headers,
            timeout=30.0,
        )
        if resp.status_code == 429:
            print("[OA CORE] Rate limited (429).")
            return []
        if resp.status_code != 200:
            print(f"[OA CORE] HTTP {resp.status_code}")
            return []
        data = resp.json()
    except Exception as e:
        print(f"[OA CORE] Error: {e}")
        return []

    articles = []
    results = data.get("results", []) if isinstance(data, dict) else []
    for item in results:
        if not isinstance(item, dict):
            continue

        # CORE provides download URLs for full text
        pdf_url = item.get("download_url") or ""
        source_url = item.get("source_fulltext_urls", [])
        if isinstance(source_url, list) and source_url and not pdf_url:
            pdf_url = source_url[0]

        # If no direct PDF, use the landing page URL
        landing_url = item.get("url") or ""

        if not pdf_url and not landing_url:
            continue

        # If pdf_url is not a real PDF link but landing_url exists, use landing_url
        if not pdf_url and landing_url:
            pdf_url = landing_url

        authors_raw = item.get("authors", [])
        authors = []
        if isinstance(authors_raw, list):
            for a in authors_raw[:5]:
                if isinstance(a, dict):
                    name = a.get("name", "")
                else:
                    name = str(a)
                if name:
                    authors.append(name)

        articles.append({
            "title": item.get("title", "Untitled"),
            "authors": authors,
            "year": item.get("year_published") or item.get("year"),
            "journal": item.get("publisher", ""),
            "doi": item.get("doi", ""),
            "abstract": item.get("abstract", ""),
            "cited_by_count": item.get("citation_count", 0),
            "is_open_access": True,
            "pdf_url": pdf_url,
            "oa_url": landing_url or pdf_url,
            "source": "CORE",
            "license": item.get("license", ""),
        })
    return articles


# ---------------------------------------------------------------------------
# Source 4: DOAJ - Directory of Open Access Journals (6M+ articles)
# ---------------------------------------------------------------------------

async def _search_doaj_oa(query, max_results, client):
    """Search DOAJ for open access articles."""
    encoded_query = quote_plus(query)
    page_size = min(max_results * 2, 50)
    url = f"https://doaj.org/api/search/articles/{encoded_query}?page=1&pageSize={page_size}"

    try:
        resp = await client.get(url, timeout=30.0)
        if resp.status_code == 429:
            print("[OA DOAJ] Rate limited (429).")
            return []
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print(f"[OA DOAJ] Error: {e}")
        return []

    articles = []
    for item in data.get("results", []):
        bibjson = item.get("bibjson", {}) or {}

        # DOAJ provides links array with fulltext URLs
        links = bibjson.get("links", [])
        pdf_url = ""
        landing_url = ""
        for link in links:
            link_type = link.get("type", "").lower()
            link_url = link.get("url", "")
            if "pdf" in link_type or link_url.endswith(".pdf"):
                pdf_url = link_url
            elif not landing_url:
                landing_url = link_url

        if not pdf_url and not landing_url:
            continue

        if not pdf_url:
            pdf_url = landing_url

        authors = []
        for a in bibjson.get("author", [])[:5]:
            name = a.get("name", "")
            if name:
                authors.append(name)

        journal_info = bibjson.get("journal", {}) or {}
        year = None
        year_month = bibjson.get("year") or journal_info.get("year")
        if year_month:
            try:
                year = int(str(year_month)[:4])
            except (ValueError, TypeError):
                year = None

        articles.append({
            "title": bibjson.get("title", "Untitled"),
            "authors": authors,
            "year": year,
            "journal": journal_info.get("title", ""),
            "doi": bibjson.get("identifier", {}).get("doi", ""),
            "abstract": bibjson.get("abstract", ""),
            "cited_by_count": 0,
            "is_open_access": True,
            "pdf_url": pdf_url,
            "oa_url": landing_url or pdf_url,
            "source": "DOAJ",
            "license": journal_info.get("license", [{}])[0].get("type", "") if journal_info.get("license") else "",
        })
    return articles


# ---------------------------------------------------------------------------
# Source 5: arXiv (2.4M+ preprints, STEM fields)
# ---------------------------------------------------------------------------

async def _search_arxiv_oa(query, max_results, client):
    """Search arXiv for preprints with PDF downloads."""
    encoded_query = quote_plus(query)
    max_fetch = min(max_results * 2, 30)
    url = f"http://export.arxiv.org/api/query?search_query=all:{encoded_query}&start=0&max_results={max_fetch}"

    try:
        resp = await client.get(url, timeout=30.0)
        if resp.status_code != 200:
            print(f"[OA arXiv] HTTP {resp.status_code}")
            return []
        xml_text = resp.text
    except Exception as e:
        print(f"[OA arXiv] Error: {e}")
        return []

    articles = []
    try:
        root = ET.fromstring(xml_text)
        # arXiv uses Atom namespace
        ns = {"atom": "http://www.w3.org/2005/Atom", "arxiv": "http://arxiv.org/schemas/atom"}

        for entry in root.findall("atom:entry", ns):
            title = entry.findtext("atom:title", "", ns).strip().replace("\n", " ")
            summary = entry.findtext("atom:summary", "", ns).strip().replace("\n", " ")
            published = entry.findtext("atom:published", "", ns)
            year = None
            if published:
                try:
                    year = int(published[:4])
                except ValueError:
                    pass

            # arXiv PDF link
            pdf_url = ""
            landing_url = ""
            for link in entry.findall("atom:link", ns):
                link_type = link.get("type", "")
                link_href = link.get("href", "")
                if "pdf" in link_type:
                    pdf_url = link_href
                elif link_href and not landing_url:
                    landing_url = link_href

            if not pdf_url:
                # arXiv always has PDF at /pdf/ endpoint
                arxiv_id = ""
                id_elem = entry.findtext("atom:id", "", ns)
                if id_elem:
                    arxiv_id = id_elem.split("/abs/")[-1] if "/abs/" in id_elem else id_elem.split("/")[-1]
                if arxiv_id:
                    pdf_url = f"https://arxiv.org/pdf/{arxiv_id}.pdf"

            if not landing_url:
                landing_url = entry.findtext("atom:id", "", ns)

            if not pdf_url and not landing_url:
                continue

            authors = []
            for author in entry.findall("atom:author", ns)[:5]:
                name = author.findtext("atom:name", "", ns)
                if name:
                    authors.append(name)

            # Extract DOI if present
            doi = ""
            doi_elem = entry.find("arxiv:doi", ns)
            if doi_elem is not None:
                doi = doi_elem.text or ""

            articles.append({
                "title": title or "Untitled",
                "authors": authors,
                "year": year,
                "journal": "arXiv preprint",
                "doi": doi,
                "abstract": summary,
                "cited_by_count": 0,
                "is_open_access": True,
                "pdf_url": pdf_url,
                "oa_url": landing_url or pdf_url,
                "source": "arXiv",
                "license": "arXiv",
            })
    except ET.ParseError as e:
        print(f"[OA arXiv] XML parse error: {e}")
        return []

    return articles


# ---------------------------------------------------------------------------
# Source 6: Crossref (150M+ records, OA filtered)
# ---------------------------------------------------------------------------

async def _search_crossref_oa(query, max_results, client):
    """Search Crossref for open access articles with license info."""
    params = {
        "query": query,
        "rows": min(max_results * 2, 50),
        "mailto": CONTACT_EMAIL,
        "select": "DOI,title,author,published-print,published-online,container-title,abstract,is-referenced-by-count,license,link",
    }
    try:
        resp = await client.get("https://api.crossref.org/works", params=params, timeout=30.0)
        if resp.status_code == 429:
            print("[OA Crossref] Rate limited (429).")
            return []
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        print(f"[OA Crossref] Error: {e}")
        return []

    articles = []
    for item in data.get("message", {}).get("items", []):
        # Check for OA license (Creative Commons, etc.)
        licenses = item.get("license", []) or []
        is_oa = any(
            "creativecommons" in lic.get("URL", "").lower()
            for lic in licenses
        )
        if not is_oa:
            continue

        # Try to find a full-text PDF link
        pdf_url = ""
        links = item.get("link", []) or []
        for link in links:
            content_type = link.get("content-type", "").lower()
            if "pdf" in content_type:
                pdf_url = link.get("URL", "")
                break

        if not pdf_url and links:
            # Use first available full-text link
            pdf_url = links[0].get("URL", "")

        if not pdf_url:
            continue

        title_list = item.get("title", [])
        title = title_list[0] if title_list else "Untitled"

        authors = []
        for a in item.get("author", [])[:5]:
            given = a.get("given", "")
            family = a.get("family", "")
            name = f"{given} {family}".strip()
            if name:
                authors.append(name)

        year = None
        date_obj = item.get("published-print") or item.get("published-online") or {}
        date_parts = date_obj.get("date-parts", [[]])
        if date_parts and date_parts[0]:
            year = date_parts[0][0]

        container = item.get("container-title", [])
        journal = container[0] if container else ""

        # Clean abstract (Crossref wraps in <jats:p> tags)
        abstract = item.get("abstract", "")
        if abstract:
            abstract = re.sub(r'<[^>]+>', '', abstract)

        articles.append({
            "title": title,
            "authors": authors,
            "year": year,
            "journal": journal,
            "doi": item.get("DOI", ""),
            "abstract": abstract,
            "cited_by_count": item.get("is-referenced-by-count", 0),
            "is_open_access": True,
            "pdf_url": pdf_url,
            "oa_url": pdf_url,
            "source": "Crossref",
        })
    return articles


# ---------------------------------------------------------------------------
# Source 7: Academia.edu (47M+ papers, link-based search)
# ---------------------------------------------------------------------------

async def _search_academia_edu(query, max_results, client):
    """Search Academia.edu for papers.

    Academia.edu does not provide a public REST API. We use their search page
    and extract results. If scraping fails, we provide a direct search link
    so users can access the source directly.
    """
    encoded_query = quote_plus(query)
    search_url = f"https://www.academia.edu/search?q={encoded_query}"

    # Try to fetch the search page and extract paper links
    headers = {"User-Agent": BROWSER_UA}
    try:
        resp = await client.get(search_url, headers=headers, timeout=20.0)
        if resp.status_code != 200:
            print(f"[OA Academia.edu] HTTP {resp.status_code}")
            # Still return a search link so users can access the source
            return [{
                "title": f"Search Academia.edu for: {query}",
                "authors": [],
                "year": None,
                "journal": "Academia.edu",
                "doi": "",
                "abstract": f"Click 'Open in Browser' to search Academia.edu (47M+ papers) for this topic.",
                "cited_by_count": 0,
                "is_open_access": True,
                "pdf_url": "",
                "oa_url": search_url,
                "source": "Academia.edu",
                "license": "",
            }]

        html = resp.text
        articles = []

        # Try to extract paper titles and links from the search results
        # Academia.edu search results contain data in JSON or HTML structure
        # Pattern: look for links to /documents/ or /Attachments/
        paper_pattern = re.findall(
            r'href="(/Documents/[^"]+)"[^>]*>([^<]+)',
            html, re.IGNORECASE
        )
        if not paper_pattern:
            # Alternative pattern for newer Academia.edu layout
            paper_pattern = re.findall(
                r'"(?:title|name)":\s*"([^"]+)".*?"(?:url|link)":\s*"(/Documents/[^"]+)"',
                html, re.IGNORECASE
            )

        seen_titles = set()
        for link, title in paper_pattern[:max_results]:
            title = title.strip()
            if not title or title in seen_titles:
                continue
            seen_titles.add(title)
            full_url = f"https://www.academia.edu{link}" if link.startswith("/") else link

            articles.append({
                "title": title,
                "authors": [],
                "year": None,
                "journal": "Academia.edu",
                "doi": "",
                "abstract": "Paper from Academia.edu. Click to access the full text.",
                "cited_by_count": 0,
                "is_open_access": True,
                "pdf_url": "",
                "oa_url": full_url,
                "source": "Academia.edu",
                "license": "",
            })

        # Always include the search link as the last result
        if not articles or len(articles) < 3:
            articles.append({
                "title": f"Browse more results on Academia.edu for: {query}",
                "authors": [],
                "year": None,
                "journal": "Academia.edu",
                "doi": "",
                "abstract": f"Search Academia.edu (47M+ papers) for this topic. Opens in a new tab.",
                "cited_by_count": 0,
                "is_open_access": True,
                "pdf_url": "",
                "oa_url": search_url,
                "source": "Academia.edu",
                "license": "",
            })

        return articles

    except Exception as e:
        print(f"[OA Academia.edu] Error: {e}")
        # Return at least a search link
        return [{
            "title": f"Search Academia.edu for: {query}",
            "authors": [],
            "year": None,
            "journal": "Academia.edu",
            "doi": "",
            "abstract": f"Click 'Open in Browser' to search Academia.edu (47M+ papers) for this topic.",
            "cited_by_count": 0,
            "is_open_access": True,
            "pdf_url": "",
            "oa_url": search_url,
            "source": "Academia.edu",
            "license": "",
        }]


def _reconstruct_abstract(inverted_index):
    if not inverted_index:
        return None
    positions = []
    for word, idxs in inverted_index.items():
        for idx in idxs:
            positions.append((idx, word))
    positions.sort()
    return " ".join(w for _, w in positions) if positions else None


async def download_pdf(url: str) -> tuple:
    """Download a PDF from a URL and return (content, filename, content_type).

    Handles common issues with academic PDF hosts:
      - Uses a browser-like User-Agent (many hosts block non-browser agents)
      - Follows redirects
      - Verifies the response is actually a PDF (not an HTML landing page)
      - If an HTML page is returned, attempts to extract the real PDF link
      - Retries with SSL verification disabled as a fallback
    """
    browser_headers = {
        "User-Agent": BROWSER_UA,
        "Accept": "application/pdf,*/*",
        "Accept-Language": "en-US,en;q=0.9",
    }

    # ---- Attempt 1: Normal download with browser headers ----
    try:
        async with httpx.AsyncClient(timeout=120.0, follow_redirects=True, headers=browser_headers) as client:
            resp = await client.get(url)
            resp.raise_for_status()
            content = resp.content
            content_type = resp.headers.get("content-type", "").lower()

            # Check if we got an actual PDF (by magic bytes and/or content-type)
            is_pdf = content[:5] == b"%PDF-" or "application/pdf" in content_type

            if is_pdf:
                filename = _extract_filename(resp, url)
                return content, filename, "application/pdf"

            # If we got HTML, try to extract a PDF link from it
            if "text/html" in content_type or content[:1] in (b"<", b"\n", b" "):
                pdf_url = _extract_pdf_link_from_html(content.decode("utf-8", errors="ignore"), url)
                if pdf_url and pdf_url != url:
                    print(f"[download_pdf] Extracted PDF URL from HTML: {pdf_url}")
                    # Recurse with the extracted URL
                    return await download_pdf(pdf_url)

            # Not a PDF and no link found — raise an informative error
            raise ValueError(
                f"The URL did not return a PDF (got {content_type or 'unknown type'}, "
                f"{len(content)} bytes). The article may require direct browser access."
            )

    except httpx.HTTPStatusError:
        raise
    except httpx.ConnectError as e:
        print(f"[download_pdf] Connection error: {e}. Retrying with SSL verification disabled.")
    except httpx.HTTPError as e:
        if "ssl" not in str(e).lower() and "certificate" not in str(e).lower():
            raise
        print(f"[download_pdf] SSL error: {e}. Retrying with SSL verification disabled.")

    # ---- Attempt 2: Retry with SSL verification disabled ----
    async with httpx.AsyncClient(timeout=120.0, follow_redirects=True, headers=browser_headers, verify=False) as client:
        resp = await client.get(url)
        resp.raise_for_status()
        content = resp.content
        content_type = resp.headers.get("content-type", "").lower()

        is_pdf = content[:5] == b"%PDF-" or "application/pdf" in content_type

        if is_pdf:
            filename = _extract_filename(resp, url)
            return content, filename, "application/pdf"

        if "text/html" in content_type:
            pdf_url = _extract_pdf_link_from_html(content.decode("utf-8", errors="ignore"), url)
            if pdf_url and pdf_url != url:
                print(f"[download_pdf] Extracted PDF URL from HTML (SSL-disabled): {pdf_url}")
                return await download_pdf(pdf_url)

        raise ValueError(
            f"The URL did not return a PDF (got {content_type or 'unknown type'}, "
            f"{len(content)} bytes). The article may require direct browser access."
        )


def _extract_filename(resp, url: str) -> str:
    """Extract a filename from response headers or URL."""
    cd = resp.headers.get("content-disposition", "")
    if cd:
        match = re.search(r'filename\*?=["\']?(?:UTF-8\'\')?([^"\';\s]+)', cd, re.IGNORECASE)
        if match:
            filename = match.group(1).strip()
            if filename:
                if not filename.endswith(".pdf"):
                    filename += ".pdf"
                return filename
    # Derive from URL
    url_path = url.split("?")[0].split("/")[-1]
    if url_path and "." in url_path:
        if not url_path.endswith(".pdf"):
            url_path += ".pdf"
        return url_path
    return "THEeye_article.pdf"


def _extract_pdf_link_from_html(html: str, base_url: str) -> str | None:
    """Try to find a direct PDF link from an HTML page.

    Checks common patterns:
      - <meta name="citation_pdf_url" content="...">
      - <meta name="fulltext_pdf_url" content="...">
      - <a href="*.pdf">
      - og:url meta tag pointing to a PDF
    """
    # 1. citation_pdf_url meta tag (used by many journal systems)
    match = re.search(r'<meta\s+name=["\']citation_pdf_url["\']\s+content=["\']([^"\']+)["\']', html, re.IGNORECASE)
    if match:
        return _resolve_url(match.group(1), base_url)

    # 2. fulltext_pdf_url meta tag
    match = re.search(r'<meta\s+name=["\']fulltext_pdf_url["\']\s+content=["\']([^"\']+)["\']', html, re.IGNORECASE)
    if match:
        return _resolve_url(match.group(1), base_url)

    # 3. Any anchor tag with .pdf href
    pdf_matches = re.findall(r'<a\s+[^>]*href=["\']([^"\']+\.pdf[^"\']*)["\']', html, re.IGNORECASE)
    if pdf_matches:
        return _resolve_url(pdf_matches[0], base_url)

    # 4. og:url meta tag
    match = re.search(r'<meta\s+property=["\']og:url["\']\s+content=["\']([^"\']+\.pdf[^"\']*)["\']', html, re.IGNORECASE)
    if match:
        return _resolve_url(match.group(1), base_url)

    return None


def _resolve_url(url: str, base_url: str) -> str:
    """Resolve a relative URL against a base URL."""
    if url.startswith("http://") or url.startswith("https://"):
        return url
    if url.startswith("//"):
        return "https:" + url
    if url.startswith("/"):
        # Get the origin from base_url
        parsed = urlparse(base_url)
        return f"{parsed.scheme}://{parsed.netloc}{url}"
    # Relative path
    base_dir = base_url.rsplit("/", 1)[0]
    return base_dir + "/" + url


# ---------------------------------------------------------------------------
# Roadmap Generation
# ---------------------------------------------------------------------------

def generate_roadmap(document_type: str, format: str, topic: str, field: str = "") -> dict:
    """Generate a full document roadmap for the specified type and format."""
    gen_func = ROADMAP_GENERATORS.get(document_type)
    if not gen_func:
        return {
            "error": f"Unknown document type: {document_type}. Available: {list(ROADMAP_GENERATORS.keys())}"
        }

    sections, fmt_desc = gen_func(topic, format, field)

    # Calculate total estimated words
    total_words = sum(s["est_words"] for s in sections)

    # Build roadmap markdown
    md_lines = [f"# Document Roadmap: {topic}", ""]
    md_lines.append(f"**Document Type:** {DOCUMENT_TYPES[document_type]['label']}")
    md_lines.append(f"**Format:** {format}")
    md_lines.append(f"**Field:** {field or 'Not specified'}")
    md_lines.append(f"**Estimated Total Words:** {total_words:,}")
    md_lines.append(f"**Number of Sections:** {len(sections)}")
    md_lines.append("")
    md_lines.append(f"**Format Description:** {fmt_desc}")
    md_lines.append("")
    md_lines.append("---")
    md_lines.append("")

    for i, section in enumerate(sections, 1):
        md_lines.append(f"## {section['title']}")
        md_lines.append(f"**Purpose:** {section['purpose']}")
        md_lines.append(f"**Estimated Words:** {section['est_words']:,}")
        md_lines.append(f"**Writing Guidelines:** {section['guidelines']}")
        md_lines.append("")

    md_lines.append("---")
    md_lines.append("")
    md_lines.append(f"*{DISCLAIMER}*")

    return {
        "document_type": document_type,
        "document_type_label": DOCUMENT_TYPES[document_type]["label"],
        "format": format,
        "format_description": fmt_desc,
        "topic": topic,
        "field": field,
        "sections": sections,
        "total_estimated_words": total_words,
        "total_sections": len(sections),
        "roadmap_markdown": "\n".join(md_lines),
        "disclaimer": DISCLAIMER,
    }


def get_document_types() -> dict:
    """Return all available document types and their formats."""
    result = {}
    for key, val in DOCUMENT_TYPES.items():
        result[key] = {
            "label": val["label"],
            "description": val["description"],
            "formats": val["formats"],
        }
    return result


def get_research_fields() -> dict:
    """Return all available research fields."""
    result = {}
    for key, val in RESEARCH_FIELDS.items():
        result[key] = {
            "label": val["label"],
            "sub_areas": val["sub_areas"],
        }
    return result
