"""
THEeye - Drafting Assistant Service
Generates academic draft sections grounded in retrieved sources.

IMPORTANT: All generated drafts are ASSISTANCE drafts, not final text.
Every draft includes a disclosure statement. The researcher must review,
verify, and revise all content before submission.

Uses template-based synthesis from actual paper data (no external LLM required).
For LLM-powered drafting, set use_llm=True and configure an API key.
"""

from datetime import datetime, timezone
from typing import Optional
from .models import Paper, ExtractedData, DraftRequest, DraftResponse


DISCLAIMER = (
    "DRAFT GENERATED BY THEeye — AI-ASSISTED RESEARCH PLATFORM. "
    "This text was synthesized from retrieved source papers and must be reviewed, "
    "verified, and revised by the human author(s) before any submission. "
    "AI assistance must be disclosed in the manuscript per journal policy. "
    "AI is not an author and cannot take responsibility for the work."
)


# ---------------------------------------------------------------------------
# Citation helpers
# ---------------------------------------------------------------------------

def _format_authors(authors: list, max_authors: int = 3) -> str:
    """Format author names for citations (APA-style)."""
    if not authors:
        return "Unknown"
    names = [a.name if isinstance(a, dict) else a.name for a in authors[:max_authors]]
    if len(authors) > max_authors:
        return f"{names[0]} et al."
    if len(names) == 1:
        return names[0]
    return ", ".join(names[:-1]) + " & " + names[-1]


def _build_citation_list(papers: list[Paper]) -> list[dict]:
    """Build numbered citation list from papers."""
    citations = []
    for i, p in enumerate(papers, 1):
        citations.append({
            "ref_number": i,
            "authors": _format_authors(p.authors),
            "year": p.year or "n.d.",
            "title": p.title,
            "journal": p.journal or "N/A",
            "doi": p.doi or "",
            "quartile": p.quartile or "N/A",
        })
    return citations


def _in_text_citation(paper: Paper, ref_num: int) -> str:
    """Generate an in-text citation like (Smith et al., 2020) [1]."""
    author = _format_authors(paper.authors, max_authors=2)
    year = paper.year or "n.d."
    return f"({author}, {year}) [{ref_num}]"


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------

def _generate_literature_review(topic: str, papers: list[Paper],
                                extracted: list[ExtractedData],
                                max_words: int) -> str:
    """Generate an advanced, thematically organized literature review draft.

    The review is structured as a professional academic synthesis: a framing
    introduction, thematic sub-sections that group papers by their substantive
    focus (detected via keyword analysis of titles, abstracts, concepts and
    TLDRs), and a closing ``Synthesis and Research Gaps`` section. Each sub-
    section compares and contrasts findings, evaluates methodological choices,
    and embeds inline citations produced by :func:`_in_text_citation`.
    """
    if not papers:
        return "No papers available for literature review. Please search first.\n"

    # Map paper title -> extracted data for quick lookup
    extracted_by_title: dict = {e.paper_title: e for e in extracted}

    # ------------------------------------------------------------------
    # Thematic grouping based on keywords in titles/abstracts/concepts
    # ------------------------------------------------------------------
    theme_keywords: dict[str, list[str]] = {
        "Institutional Quality and Governance": [
            "institutional", "governance", "corruption", "rule of law",
            "regulatory quality", "political stability", "democracy",
            "government effectiveness",
        ],
        "Economic Growth and Development": [
            "economic growth", "gdp", "growth rate", "development",
            "convergence", "productivity", "economic development",
        ],
        "Foreign Direct Investment and Capital Flows": [
            "fdi", "foreign direct investment", "investment inflow",
            "capital flow", "portfolio investment", "capital mobility",
        ],
        "Trade and Economic Openness": [
            "trade", "openness", "export", "import", "tariff",
            "trade liberalization", "trade openness", "globalization",
        ],
        "Innovation, Technology, and Digitalization": [
            "innovation", "r&d", "research and development", "technology",
            "patent", "digital", "ict", "digitalization",
        ],
        "Human Capital and Education": [
            "human capital", "education", "skill", "labor", "workforce",
            "schooling", "training",
        ],
        "Financial Development and Markets": [
            "financial develop", "banking", "credit", "stock market",
            "financial market", "financial depth", "financial inclusion",
        ],
        "Inequality, Poverty, and Distribution": [
            "inequality", "poverty", "income distribution", "gini",
            "income gap", "redistribution",
        ],
        "Environmental and Sustainability Outcomes": [
            "environment", "emission", "climate", "sustainability",
            "esg", "carbon", "pollution", "green",
        ],
        "Macroeconomic Stability and Policy": [
            "inflation", "monetary", "fiscal", "exchange rate",
            "macroeconomic", "stability",
        ],
    }

    def _paper_text(p: Paper) -> str:
        """Concatenate all text fields used for theme detection."""
        parts = [p.title or "", p.abstract or "", p.tldr or ""]
        parts.extend(p.concepts or [])
        parts.extend(p.keywords or [])
        return " ".join(parts).lower()

    def _score_theme(text: str, keywords: list[str]) -> int:
        return sum(text.count(kw.lower()) for kw in keywords)

    theme_groups: dict[str, list[tuple[int, Paper, Optional[ExtractedData]]]] = {}
    general_group: list[tuple[int, Paper, Optional[ExtractedData]]] = []

    for i, p in enumerate(papers, 1):
        text = _paper_text(p)
        best_theme, best_score = None, 0
        for theme, kws in theme_keywords.items():
            score = _score_theme(text, kws)
            if score > best_score:
                best_theme, best_score = theme, score
        entry = (i, p, extracted_by_title.get(p.title))
        if best_theme and best_score > 0:
            theme_groups.setdefault(best_theme, []).append(entry)
        else:
            general_group.append(entry)

    # ------------------------------------------------------------------
    # Helpers for prose synthesis
    # ------------------------------------------------------------------
    def _clean(text: Optional[str]) -> str:
        """Strip surrounding whitespace and a trailing period/semicolon."""
        if not text:
            return ""
        s = text.strip()
        if s and s[-1] in ".;":
            s = s[:-1]
        return s

    def _paper_summary(ref_num: int, p: Paper,
                       ext: Optional[ExtractedData]) -> str:
        """Build a single synthesized sentence cluster for one paper.

        A reporting connector is chosen so the citation reads naturally: if the
        summary is already a self-contained statement (begins with a pronoun,
        article, or method word) it is introduced with ``According to ...``;
        otherwise it is treated as a claim and attached via ``... find that``.
        """
        cite = _in_text_citation(p, ref_num)
        # Prefer TLDR; fall back to abstract snippet
        if p.tldr:
            summary = _clean(p.tldr)
        elif p.abstract:
            snippet = _clean(p.abstract)
            if len(snippet) > 240:
                snippet = snippet[:240] + "..."
            summary = snippet
        else:
            summary = ""
        if not summary:
            summary = "the study contributes empirical evidence to the field"
        summary = summary[0].lower() + summary[1:]
        first_word = summary.split()[0].lower() if summary else ""
        self_contained = first_word in {
            "this", "we", "the", "our", "these", "a", "an", "using", "by",
            "in", "across", "employing", "drawing", "based",
        }
        if self_contained:
            lead = f"According to {cite}, {summary}"
        else:
            lead = f"{cite} find that {summary}"
        if not lead.endswith("."):
            lead += "."
        parts = [lead]
        method = ext.methodology if ext and ext.methodology else None
        sample = ext.sample_size if ext and ext.sample_size else None
        if method:
            clause = f"Methodologically, the authors employ {method.lower()}"
            if sample:
                clause += f" with {sample.lower()}"
            parts.append(clause + ".")
        if ext and ext.key_findings:
            finding = _clean(ext.key_findings[0]).lower()
            if finding:
                parts.append(f"A central finding is that {finding}.")
        return " ".join(parts)

    # ------------------------------------------------------------------
    # Build the review
    # ------------------------------------------------------------------
    sections: list[str] = []
    sections.append(f"## Literature Review: {topic}\n")

    # --- Introduction paragraph that frames the review ---
    q1 = sum(1 for p in papers if p.quartile == "Q1")
    q2 = sum(1 for p in papers if p.quartile == "Q2")
    total_cites = sum(p.cited_by_count for p in papers)
    years = [p.year for p in papers if p.year]
    year_span = f" spanning {min(years)}-{max(years)}" if years else ""

    intro = (
        f"The scholarly literature on {topic.lower()} has expanded considerably, "
        f"reflecting the topic's centrality to contemporary debates in economics, "
        f"governance, and public policy. This review synthesizes {len(papers)} "
        f"peer-reviewed studies{year_span}, drawing predominantly on Q1 and Q2 "
        f"publications ({q1} Q1 and {q2} Q2 sources, with a cumulative citation "
        f"count of {total_cites}). Rather than offering a merely chronological "
        f"or methodological survey, the review organizes the literature "
        f"thematically around the substantive foci that recur across the corpus. "
        f"For each thematic cluster, we synthesize the central arguments, "
        f"juxtapose competing findings, and evaluate the methodological choices "
        f"that shape the evidence base. The review closes with a synthesis "
        f"section that identifies recurrent debates, unresolved contradictions, "
        f"and avenues for future inquiry.\n\n"
    )
    sections.append(intro)

    # --- Thematic sub-sections ---
    for theme, group in theme_groups.items():
        # Sort within theme by citation count (most influential first)
        group_sorted = sorted(
            group, key=lambda g: g[1].cited_by_count, reverse=True
        )
        body: list[str] = [f"### {theme}\n\n"]

        # Paragraph 1: synthesize the cluster, lead with most influential
        para1 = (
            f"Within the cluster of studies addressing {theme.lower()}, the "
            f"literature converges on several core propositions. "
        )
        para1 += _paper_summary(*group_sorted[0]) + " "
        for ref_num, p, ext in group_sorted[1:3]:
            para1 += _paper_summary(ref_num, p, ext) + " "
        body.append(para1 + "\n\n")

        # Paragraph 2: comparison/contrast and methodological critique
        para2 = (
            f"A comparative reading of these contributions reveals both "
            f"convergence and divergence. "
        )
        findings_list = []
        for ref_num, p, ext in group_sorted:
            if ext and ext.key_findings:
                findings_list.append(
                    f"{_in_text_citation(p, ref_num)} report that "
                    f"{_clean(ext.key_findings[0]).lower()}"
                )
        if len(findings_list) >= 2:
            para2 += (
                f"While {findings_list[0]}, {findings_list[1]}. "
                f"This divergence illustrates how contextual and specification "
                f"choices qualify the reported effects. "
            )
        elif len(findings_list) == 1:
            para2 += (
                f"Notably, {findings_list[0]}, yet the limited number of "
                f"comparable estimates precludes firm generalization. "
            )
        else:
            para2 += (
                f"Although the studies share a thematic focus, their estimates "
                f"vary in magnitude and significance across samples and "
                f"specifications. "
            )
        # methodological critique
        methods_in_group = [
            (ext.methodology, ext.sample_size)
            for _, _, ext in group_sorted
            if ext and ext.methodology
        ]
        if methods_in_group:
            distinct_methods = sorted(
                {m.lower() for m, _ in methods_in_group}
            )
            para2 += (
                f"From a methodological standpoint, the cluster relies "
                f"primarily on {', '.join(distinct_methods[:3])}. "
            )
            has_longitudinal = any(
                "panel" in (m or "").lower()
                or "longitudinal" in (m or "").lower()
                for m, _ in methods_in_group
            )
            if not has_longitudinal:
                para2 += (
                    f"The relative absence of longitudinal panel designs "
                    f"constrains the causal claims that can be defensibly "
                    f"advanced. "
                )
            if any(
                tok in (s or "").lower()
                for _, s in methods_in_group for tok in ["small", "cross", "few"]
            ):
                para2 += (
                    f"Several studies rely on comparatively small or "
                    f"cross-sectional samples, raising external-validity "
                    f"concerns. "
                )
        body.append(para2 + "\n\n")

        # Paragraph 3 (optional): influence and trajectory note
        if len(group_sorted) >= 2:
            most_cited = group_sorted[0]
            least_cited = group_sorted[-1]
            para3 = (
                f"In terms of scholarly influence, "
                f"{_in_text_citation(most_cited[1], most_cited[0])} anchor this "
                f"strand (cited {most_cited[1].cited_by_count} times), while "
                f"more recent contributions such as "
                f"{_in_text_citation(least_cited[1], least_cited[0])} extend "
                f"the evidence to new contexts and specifications. Collectively, "
                f"the cluster underscores that {theme.lower()} is a constitutive "
                f"dimension of any rigorous treatment of {topic.lower()}, while "
                f"also pointing to the need for greater cross-contextual "
                f"comparability.\n\n"
            )
            body.append(para3)

        sections.append("".join(body))

    # --- General / ungrouped studies, if any ---
    if general_group:
        body = [f"### General and Multidisciplinary Contributions\n\n"]
        para = (
            f"Several studies resist neat thematic classification yet inform "
            f"the broader debate on {topic.lower()}. "
        )
        for ref_num, p, ext in general_group:
            para += _paper_summary(ref_num, p, ext) + " "
        para += (
            f"Taken together, these contributions provide conceptual "
            f"scaffolding and complementary evidence that contextualize the "
            f"thematic clusters above.\n\n"
        )
        body.append(para)
        sections.append("".join(body))

    # --- Synthesis and Research Gaps section ---
    synth = [
        f"### Synthesis and Research Gaps\n\n",
        f"Synthesizing across the thematic clusters yields three overarching "
        f"observations. First, the literature converges on the view that "
        f"{topic.lower()} cannot be understood in isolation but is embedded "
        f"in institutional, economic, and contextual configurations. Second, "
        f"despite this convergence, the evidence is marked by notable "
        f"contradictions: studies differ in the magnitude, sign, and "
        f"significance of the relationships they report, often as a function "
        f"of sample composition, variable construction, and identification "
        f"strategy. Third, the field remains methodologically uneven, with a "
        f"heavy concentration of cross-sectional designs and limited use of "
        f"causal identification.\n\n",
    ]

    # Identify contradictions more concretely
    findings_by_theme: dict[str, list[str]] = {}
    for theme, group in theme_groups.items():
        for _, _, ext in group:
            if ext and ext.key_findings:
                findings_by_theme.setdefault(theme, []).extend(
                    ext.key_findings[:1]
                )
    if findings_by_theme:
        themes_named = ", ".join(list(findings_by_theme.keys())[:3])
        synth.append(
            f"More specifically, within thematic clusters such as "
            f"{themes_named}, the reported effects range from positive and "
            f"significant to negligible or conditional, reflecting differences "
            f"in operationalization and country coverage rather than purely "
            f"substantive disagreement. "
        )

    # Methodological gaps
    gaps: list[str] = []
    has_longitudinal = any(
        "panel" in (e.methodology or "").lower()
        or "longitudinal" in (e.methodology or "").lower()
        for e in extracted
    )
    if not has_longitudinal:
        gaps.append(
            "the under-utilization of longitudinal panel designs, which "
            "restricts causal inference"
        )
    regions_covered = {e.data_source for e in extracted if e.data_source}
    if len(regions_covered) < 3:
        gaps.append(
            "limited geographic coverage, which compromises the external "
            "validity and generalizability of findings"
        )
    has_causal = any(
        tok in (e.methodology or "").lower()
        for e in extracted
        for tok in ["iv", "instrument", "2sls", "did",
                   "difference-in-difference", "regression discontinuity",
                   "rct", "random"]
    )
    if not has_causal:
        gaps.append(
            "a scarcity of causal identification strategies "
            "(e.g., instrumental variables, difference-in-differences, "
            "regression discontinuity)"
        )
    if gaps:
        synth.append(
            f"Methodologically, the reviewed corpus exhibits several gaps: "
            f"{'; '.join(gaps)}. "
        )

    # Future research directions
    synth.append(
        f"\n\nFuture research should therefore (i) expand the geographic and "
        f"temporal scope of analysis, privileging panel structures that permit "
        f"both entity and time fixed effects; (ii) deploy credible causal "
        f"identification strategies to move beyond associational claims; "
        f"(iii) test the robustness of established results to alternative "
        f"operationalizations and model specifications; and (iv) attend more "
        f"systematically to heterogeneity across institutional, regional, and "
        f"developmental contexts. Addressing these priorities would consolidate "
        f"the evidence base on {topic.lower()} and yield more policy-relevant, "
        f"generalizable conclusions.\n"
    )
    sections.append("".join(synth))

    text = "\n".join(sections)
    # Truncate if exceeding max_words (approximate)
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]) + "..."
    return text


def _generate_introduction(topic: str, papers: list[Paper],
                           extracted: list[ExtractedData],
                           max_words: int) -> str:
    """Generate an introduction draft."""
    if not papers:
        return "No papers available. Please search first.\n"

    # Find the most cited paper for the opening hook
    sorted_papers = sorted(papers, key=lambda p: p.cited_by_count, reverse=True)
    top_paper = sorted_papers[0]

    parts = [
        f"## Introduction\n\n",
        f"The relationship between {topic.lower()} and economic outcomes has become "
        f"increasingly central to both academic discourse and policy debates. "
        f"As {_in_text_citation(top_paper, 1)} note, understanding these dynamics is critical "
        f"for informed decision-making. ",
    ]

    # Context paragraph
    parts.append(
        f"\n\nIn recent decades, the global landscape has undergone profound transformations, "
        f"creating both opportunities and challenges for researchers studying {topic.lower()}. "
        f"Theoretical frameworks have evolved from early models to more nuanced approaches "
        f"that account for institutional heterogeneity, structural constraints, and "
        f"contextual specificities. "
    )

    # Cite a few key papers
    for i, p in enumerate(sorted_papers[1:4], 2):
        parts.append(f"{_in_text_citation(p, i)} ")
        if p.tldr:
            parts.append(f"highlight that {p.tldr.lower()} ")
        elif p.abstract:
            snippet = p.abstract[:150].lower()
            parts.append(f"contribute insights noting that {snippet}... ")

    # Problem statement
    parts.append(
        f"\n\nDespite this growing body of literature, significant gaps remain in our understanding "
        f"of {topic.lower()}. Many existing studies are constrained by limited geographic scope, "
        f"short time horizons, or methodological limitations that restrict causal inference. "
        f"Moreover, the heterogeneity of findings across contexts suggests that "
        f"country-specific and regional factors play a mediating role that warrants deeper investigation.\n\n"
    )

    # Contribution statement
    parts.append(
        f"This study addresses these gaps by examining {topic.lower()} using a comprehensive "
        f"approach that draws on the methodological strengths identified in the reviewed literature. "
        f"Specifically, it makes three contributions: (1) it extends the empirical evidence to "
        f"underexplored contexts; (2) it employs robust identification strategies; and "
        f"(3) it provides policy-relevant insights grounded in the theoretical framework "
        f"developed below.\n"
    )

    text = "".join(parts)
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]) + "..."
    return text


def _generate_abstract(topic: str, papers: list[Paper],
                       extracted: list[ExtractedData],
                       max_words: int) -> str:
    """Generate a structured abstract draft."""
    if not papers:
        return "No papers available. Please search first.\n"

    # Gather methodology info
    methods = [e.methodology for e in extracted if e.methodology]
    method_str = ", ".join(set(methods[:3])) if methods else "quantitative methods"

    samples = [e.sample_size for e in extracted if e.sample_size]
    sample_str = samples[0] if samples else "the available sample"

    # Key findings
    all_findings = []
    for e in extracted[:3]:
        all_findings.extend(e.key_findings[:1])
    findings_str = " ".join(all_findings[:3]) if all_findings else \
        f"the analysis reveals significant relationships relevant to {topic.lower()}."

    abstract = (
        f"## Abstract\n\n"
        f"This study examines {topic.lower()}, drawing on evidence from "
        f"{len(papers)} peer-reviewed studies. Employing {method_str.lower()} with "
        f"{sample_str}, we investigate the key determinants and outcomes associated with "
        f"{topic.lower()}. {findings_str} The findings contribute to the existing literature "
        f"by providing nuanced evidence that accounts for contextual heterogeneity. "
        f"Policy implications and directions for future research are discussed.\n"
    )

    words = abstract.split()
    if len(words) > max_words:
        abstract = " ".join(words[:max_words]) + "..."
    return abstract


def _generate_methodology(topic: str, papers: list[Paper],
                          extracted: list[ExtractedData],
                          max_words: int) -> str:
    """Generate a methodology draft grounded in the reviewed literature.

    The section describes the research design, data sources, variables, and
    estimation techniques, drawing on the methodological information extracted
    from the source papers.
    """
    if not papers:
        return "No papers available. Please search first.\n"

    # Gather methodology info from extracted data
    methods = [e.methodology for e in extracted if e.methodology]
    data_sources = [e.data_source for e in extracted if e.data_source]
    samples = [e.sample_size for e in extracted if e.sample_size]
    all_vars = []
    for e in extracted:
        all_vars.extend(e.variables)

    # Deduplicate while preserving order
    seen = set()
    unique_methods = []
    for m in methods:
        key = m.lower().strip()
        if key not in seen:
            seen.add(key)
            unique_methods.append(m)
    method_str = ", ".join(unique_methods[:4]) if unique_methods else \
        "panel data analysis with fixed-effects and random-effects estimators"

    seen_ds = set()
    unique_sources = []
    for ds in data_sources:
        key = ds.lower().strip()
        if key not in seen_ds:
            seen_ds.add(key)
            unique_sources.append(ds)
    source_str = "; ".join(unique_sources[:4]) if unique_sources else \
        "World Bank World Development Indicators, IMF International Financial Statistics, and Transparency International"

    sample_str = samples[0] if samples else "annual data spanning the period 2000-2023"

    unique_vars = []
    seen_v = set()
    for v in all_vars:
        key = v.lower().strip()
        if key not in seen_v:
            seen_v.add(key)
            unique_vars.append(v)
    vars_str = ", ".join(unique_vars[:8]) if unique_vars else \
        "foreign direct investment (FDI) net inflows, GDP growth rate, institutional quality indices, trade openness, inflation, and gross capital formation"

    parts = [
        f"## Methodology\n\n",
        f"This section outlines the research design, data sources, and analytical "
        f"techniques employed to investigate {topic.lower()}. The methodological "
        f"approach is informed by the strategies adopted in the reviewed studies, "
        f"ensuring both rigor and comparability with the existing literature "
        f"{_in_text_citation(papers[0], 1)}.\n\n",
    ]

    # Research design and approach
    parts.append(f"### Research Design and Approach\n\n")
    parts.append(
        f"The study adopts a quantitative research design utilising {method_str.lower()}. "
        f"This approach is consistent with the dominant methodological paradigm in the field, "
        f"as several studies examining {topic.lower()} have employed similar frameworks "
    )
    for i, p in enumerate(papers[1:3], 2):
        parts.append(f"{_in_text_citation(p, i)} ")
    parts.append(
        f". The choice of design is motivated by the need to establish empirical "
        f"relationships among variables while controlling for unobserved heterogeneity "
        f"and potential endogeneity concerns. Both fixed-effects and random-effects "
        f"specifications are estimated, with the Hausman test guiding the selection "
        f"of the preferred model.\n\n"
    )

    # Data sources and variables
    parts.append(f"### Data Sources and Variables\n\n")
    parts.append(
        f"The analysis draws on {source_str}. The dataset comprises {sample_str}, "
        f"providing sufficient observations for robust econometric inference. "
        f"The dependent variable and key explanatory variables are constructed "
        f"following standard practices in the literature "
    )
    for i, p in enumerate(papers[3:5], 4):
        if i <= len(papers):
            parts.append(f"{_in_text_citation(p, i)} ")
    parts.append(
        f".\n\nThe core variables include: {vars_str}. Control variables are "
        f"incorporated to account for structural differences across units and "
        f"over time. All variables are transformed into natural logarithms where "
        f"appropriate to interpret coefficients as elasticities and to reduce "
        f"the influence of outliers.\n\n"
    )

    # Estimation techniques and model specification
    parts.append(f"### Estimation Techniques and Model Specification\n\n")
    parts.append(
        f"The baseline empirical model is specified as follows:\n\n"
        f"    Y_it = β₀ + β₁X_it + β₂Z_it + μ_i + λ_t + ε_it\n\n"
        f"where Y_it denotes the dependent variable for unit i at time t, "
        f"X_it represents the principal explanatory variable(s), Z_it is a "
        f"vector of controls, μ_i captures unobserved unit-specific effects, "
        f"λ_t represents time-specific effects, and ε_it is the idiosyncratic "
        f"error term. The parameters of interest are the β coefficients, "
        f"estimated using {method_str.lower()}.\n\n"
    )
    parts.append(
        f"Robustness checks include alternative model specifications, "
        f"sub-sample analysis, and diagnostic tests for serial correlation, "
        f"heteroskedasticity, and cross-sectional dependence. Where endogeneity "
        f"is a concern, instrumental variable (IV) estimation or the generalised "
        f"method of moments (GMM) estimator is employed, following the approaches "
    )
    for i, p in enumerate(papers[5:7], 6):
        if i <= len(papers):
            parts.append(f"{_in_text_citation(p, i)} ")
    parts.append(
        f". Standard errors are clustered at the unit level to account for "
        f"within-group correlation.\n"
    )

    text = "".join(parts)
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]) + "..."
    return text


def _generate_conclusion(topic: str, papers: list[Paper],
                         extracted: list[ExtractedData],
                         max_words: int) -> str:
    """Generate a conclusion draft."""
    if not papers:
        return "No papers available. Please search first.\n"

    parts = [
        f"## Conclusion\n\n",
        f"This study set out to examine {topic.lower()}, synthesizing evidence from "
        f"{len(papers)} studies published in peer-reviewed journals. "
        f"The analysis reveals several important insights.\n\n",
    ]

    # Summarize key findings
    parts.append(f"### Key Findings\n\n")
    for i, e in enumerate(extracted[:5], 1):
        if e.key_findings:
            parts.append(f"{i}. {e.key_findings[0]}\n")
        elif e.research_question:
            parts.append(f"{i}. {e.research_question}\n")

    # Policy implications
    parts.append(
        f"\n### Policy Implications\n\n"
        f"The findings carry significant policy implications. The evidence suggests that "
        f"effective approaches to {topic.lower()} require attention to institutional quality, "
        f"structural conditions, and contextual factors. Policymakers should consider "
        f"these dimensions when designing interventions.\n\n"
    )

    # Limitations and future research
    parts.append(
        f"### Limitations and Future Research\n\n"
        f"While this study contributes to the understanding of {topic.lower()}, "
        f"several limitations should be acknowledged. The scope of available data and "
        f"the methodological constraints of the reviewed studies bound the generalizability "
        f"of findings. Future research should expand geographic coverage, employ "
        f"longer time horizons, and explore causal mechanisms more deeply.\n"
    )

    text = "".join(parts)
    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words]) + "..."
    return text


def _generate_summary(topic: str, papers: list[Paper],
                      extracted: list[ExtractedData],
                      max_words: int) -> str:
    """Generate a brief summary of the literature."""
    if not papers:
        return "No papers available. Please search first.\n"

    total_citations = sum(p.cited_by_count for p in papers)
    journals = set(p.journal for p in papers if p.journal)
    q1_count = sum(1 for p in papers if p.quartile == "Q1")
    q2_count = sum(1 for p in papers if p.quartile == "Q2")

    summary = (
        f"## Summary\n\n"
        f"This review analyzed {len(papers)} studies on {topic.lower()}, "
        f"drawn from {len(journals)} journals. The corpus includes {q1_count} Q1 and "
        f"{q2_count} Q2 publications, with a combined citation count of {total_citations}, "
        f"indicating a body of high-impact literature. "
    )

    # Top findings
    if extracted:
        summary += "Key themes identified include:\n\n"
        for i, e in enumerate(extracted[:5], 1):
            finding = e.key_findings[0] if e.key_findings else \
                (e.research_question or f"Study on {topic.lower()}")
            summary += f"{i}. {finding[:200]}\n"

    summary += (
        f"\nThese findings collectively advance our understanding of {topic.lower()} "
        f"and highlight avenues for future investigation.\n"
    )

    words = summary.split()
    if len(words) > max_words:
        summary = " ".join(words[:max_words]) + "..."
    return summary


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_draft(request: DraftRequest) -> DraftResponse:
    """
    Generate an academic draft section.

    All drafts are grounded in the provided papers with proper citations.
    A disclosure disclaimer is always included.
    """
    generators = {
        "literature_review": _generate_literature_review,
        "introduction": _generate_introduction,
        "methodology": _generate_methodology,
        "abstract": _generate_abstract,
        "conclusion": _generate_conclusion,
        "summary": _generate_summary,
    }

    gen_func = generators.get(request.section_type)
    if not gen_func:
        return DraftResponse(
            section_type=request.section_type,
            topic=request.topic,
            content=f"Error: Unknown section type '{request.section_type}'. "
                    f"Supported types: {', '.join(generators.keys())}",
            citations=[],
            word_count=0,
            disclaimer=DISCLAIMER,
        )

    content = gen_func(request.topic, request.papers, request.extracted_data,
                       request.max_words)
    citations = _build_citation_list(request.papers)
    word_count = len(content.split())

    return DraftResponse(
        section_type=request.section_type,
        topic=request.topic,
        content=content,
        citations=citations,
        word_count=word_count,
        disclaimer=DISCLAIMER,
    )
